doc Refer to the Streams section from TCP stream
akka/akka pull request #21436
Opened 2016-09-10 06:11 UTC by richard-imaoka

Fixes #21308

Maybe not necessary to mention Akka HTTP from this TCP section. However, since Akka HTTP is well documented with lot more examples, I thought users get hints from the Akka HTTP section.

[Java TCP Stream IO doc](http://doc.akka.io/docs/akka/2.4/java/stream/stream-io.html)
[Scala TCP Stream IO doc](http://doc.akka.io/docs/akka/2.4/scala/stream/stream-io.html)

### After this change 
![image](https://cloud.githubusercontent.com/assets/7414320/18408361/8f1ac140-7768-11e6-9138-ac61a4bd1a38.png)

2016-09-13 14:00 UTC, patriknw commented on akka-docs/rst/java/stream/stream-io.rst
> +.. _Streams section: http://doc.akka.io/docs/akka/current/scala/stream/index.html
this should be a cross link, search for similar `:ref:`

2016-09-14 10:49 UTC, drewhk commented
LGTM

2016-09-19 21:42 UTC, richard-imaoka commented
Sorry still working on this to add diagrams + reflect comments from Patrik. Will come back to this in a few days.

2016-09-22 03:42 UTC, ktoso commented on akka-docs/rst/java/stream/stream-io.rst
> +.. _Streams section: http://doc.akka.io/docs/akka/current/scala/stream/index.html
+1

2016-09-22 03:43 UTC, ktoso requested changes
LGTM, after ref fixed

2016-09-22 15:14 UTC, richard-imaoka commented
Added images. 

Ping @BertRobben in case he has comments on the images.
![image](https://cloud.githubusercontent.com/assets/7414320/18754138/8d277536-8122-11e6-96f5-5f0abcc71400.png)

![image](https://cloud.githubusercontent.com/assets/7414320/18754030/2ca32ab6-8122-11e6-8a74-ca77a920f1fc.png)

2016-09-22 15:15 UTC, richard-imaoka commented on akka-docs/rst/java/stream/stream-io.rst
> +.. _Streams section: http://doc.akka.io/docs/akka/current/scala/stream/index.html
Fixed this.

2016-09-23 04:50 UTC, BertRobben commented
The images look great! Nice job.Now it should be much clearer for starters.

thanks,

Bert

On Thu, Sep 22, 2016 at 5:15 PM, Richard Imaoka <notifications@github.com>
wrote:

> Added images.
>
> Ping @BertRobben <https://github.com/BertRobben> in case he has comments
> on the images.
> [image: image]
> <https://cloud.githubusercontent.com/assets/7414320/18754138/8d277536-8122-11e6-96f5-5f0abcc71400.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/7414320/18754030/2ca32ab6-8122-11e6-8a74-ca77a920f1fc.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/akka/akka/pull/21436#issuecomment-248933671>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACafZkNJq5cw2o8UR5OWr9QiRU4q31h1ks5qspt1gaJpZM4J5pct>
> .
>

2016-09-30 12:28 UTC, patriknw commented
LGTM

2016-09-30 12:28 UTC, merged