Doc - Add warning note about persistence message deletion
akka/akka pull request #21486
Opened 2016-09-18 16:49 UTC by richard-imaoka

Refs #18886

2016-09-19 12:45 UTC, johanandren commented on akka-docs/rst/java/persistence.rst
> +  If you are using :ref:`persistence-query-scala`, query results will be missing deleted messages in a journal.
Ref should go to `persistence-query-java`

2016-09-19 12:46 UTC, johanandren commented
LGTM except Java link pointing to Scala docs

2016-09-19 19:18 UTC, richard-imaoka commented on akka-docs/rst/java/persistence.rst
> +  If you are using :ref:`persistence-query-scala`, query results will be missing deleted messages in a journal.
Oops, thanks for finding it out. I fixed this in thew new commit.

2016-09-20 11:52 UTC, patriknw commented on akka-docs/rst/java/persistence.rst
> +  If you are using :ref:`persistence-query-java`, query results will be missing deleted messages in a journal.
it depends on the journal implementation, I think the leveldb implementation is a completely detached materialized view. Reword to "may be missing deleted messages in a journal, depending on how deletions are implemented in the journal plugin"

2016-09-20 11:52 UTC, patriknw requested changes

2016-09-20 20:03 UTC, richard-imaoka commented on akka-docs/rst/java/persistence.rst
> +  If you are using :ref:`persistence-query-java`, query results will be missing deleted messages in a journal.
Thanks for the feedback. I modified the warning text - could you see if that looks ok?

2016-10-08 06:10 UTC, richard-imaoka commented
Hi, I responded to the review comments. Appreciate it if you can take a look when you have time.
Thanks

2016-10-08 21:06 UTC, patriknw approved these changes

2016-10-08 21:06 UTC, patriknw commented
LGTM

2016-10-08 21:07 UTC, merged

2016-10-08 21:08 UTC, ktoso commented
LGTM, thanks