WIP Quarantine gracefully downed node after some time
akka/akka pull request #21534
Opened 2016-09-23 13:40 UTC by johanandren

Refs #21521

2016-09-23 13:41 UTC, johanandren commented on akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
> +        context.system.scheduler.scheduleOnce(cluster.downingProvider.downRemovalMargin, self, DelayedQuarantine(m, previousStatus))
Not sure this is a good idea, but if the cluster singleton doesn't have a specific removalMargin configured, this is what is used as removalMargin in ClusterSingletonManager.

I'm guessing we can't really depend on the singleton manager setting here.

2016-09-23 13:41 UTC, johanandren commented
Any hints of how I could provide test coverage for this would be great.

2016-09-23 14:14 UTC, patriknw commented on akka-cluster/src/main/scala/akka/cluster/ClusterRemoteWatcher.scala
> +        context.system.scheduler.scheduleOnce(cluster.downingProvider.downRemovalMargin, self, DelayedQuarantine(m, previousStatus))
I have created a new issue for redesigning the cluster leaving process, but that's a rather big thing. Until then we need something simple that can work, and I think a simple delay like this should be enough for now.

We already have enough test coverage, singleton tests will fail.

We can't use `downRemovalMargin`. It's by default zero. We should use something like 20 - 30 seconds. It doesn't feel great to introduce a new config property for this, but hardcoded value is not so nice either.

2016-09-26 14:55 UTC, patriknw commented on akka-cluster/src/main/resources/reference.conf
> +    # When a node has been gracefully downed, let this time pass (to allow for example
has been gracefully *removed*... and then quarantine the *removed* node.

2016-09-26 14:56 UTC, patriknw commented on akka-cluster/src/main/resources/reference.conf
> +    quarantine-downed-node-after=30s
`quarantine-removed-node-after`

downing is for the unexpected crash scenario, leaving is for the graceful removal

2016-09-26 14:58 UTC, patriknw requested changes
minor rename, but otherwise it looks good

2016-09-26 17:27 UTC, johanandren commented on akka-cluster/src/main/resources/reference.conf
> +    quarantine-downed-node-after=30s
D'oh!

2016-09-27 06:33 UTC, patriknw approved these changes

2016-09-27 06:33 UTC, patriknw commented
LGTM

2016-09-28 12:04 UTC, merged