rewrite Buffer as a GraphStage
akka/akka pull request #21635
Opened 2016-10-07 12:55 UTC by Hawstein

Refs #21528

2016-10-07 14:20 UTC, ktoso commented
OK TO TEST

2016-10-07 16:28 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    }
why not just in `preStart`?

2016-10-07 20:50 UTC, johanandren reviewed
More of a set of questions than an actual review.

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      }
Vals up top thanks!

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      } else if (!(isClosed(in) || hasBeenPulled(in))) {
`!isClosed` is implied here because of the `if(isClosed` above?

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, buffer.dequeue())
Do we know the buffer isn't empty here?

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      if (isClosed(in)) {
I'd like the most common case first rather than this. One idea would to even have a separate `OutHandler` and use that after in has been closed.

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, buffer.dequeue())
We pushed an element from the buffer, so it cannot be full and in has not been pulled, shouldn't we pull?

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    var buffer: BufferImpl[T] = _
buffer should be a val and created directly in constructor, is never replaced only cleared

2016-10-07 20:50 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, elem)
So, `out` will only be available when the buffer contains elements? If not, shouldn't it dequeue-push elements from the buffer if there are elements in it?

2016-10-10 16:38 UTC, viktorklang commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    var buffer: BufferImpl[T] = _
It is in the constructor though? Of the GraphStageLogic.

2016-10-11 07:29 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    var buffer: BufferImpl[T] = _
Yes, but the actual instance is created in `preStart`, and is mutable, so this would be better as a val and instantiated right here.

2016-10-17 14:30 UTC, patriknw commented
Looks like there are some corner cases to be hardened here. Since tests are passing that is an indication that it would be good to add some more test coverage also.

2016-10-21 14:39 UTC, ktoso commented
Hey @Hawstein, would you be able to address the recent comments here?

2016-10-29 16:48 UTC, Hawstein commented
@ktoso Sorry for the long time delay, too busy to reply your comments and update the PR. Will fix it now :)

2016-10-29 16:53 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, elem)
Good catch. I just simply translated the old version to GraphStage. Ashamed for not even thinking about it.

2016-10-29 16:55 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, buffer.dequeue())
Nope. There already exists an pending pull which implied by the above `else if`

2016-10-29 16:56 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      }
Sure

2016-10-29 17:07 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    var buffer: BufferImpl[T] = _
@johanandren It does not work. It is not allowed defined the buffer as `val` in GraphStageLogic constructor. The compiler will complain.

2016-10-29 17:14 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    }
Put it in preStart now

2016-10-29 17:16 UTC, Hawstein commented
@ktoso @patriknw @johanandren The PR is updated.

2016-10-29 17:17 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        push(out, buffer.dequeue())
No, will fix it.

2016-10-31 10:13 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +    var buffer: BufferImpl[T] = _
Why would the compiler complain about that?
`val buffer = BufferImpl(size, materializer)`

In general val + mutable datastructure or var + immutable data structure is good to strive for if you have to do mutable stuff.

2016-10-31 10:15 UTC, johanandren approved these changes
LGTM with the buffer a val and instantiated in the constructor

2016-10-31 11:43 UTC, drewhk requested changes
Almost there, but there are some logic discrepancies remaining that need to be ironed out.

2016-10-31 11:43 UTC, drewhk commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +          push(out, buffer.dequeue())
how is this correct? if `isAvailable(out)` would be true, then we were already pulled. But in that case we should have already delivered a dequeued element from the buffer and hence `isAvailable(out)` cannot be true.

2016-10-31 11:43 UTC, drewhk commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +        if (buffer.nonEmpty) push(out, buffer.dequeue())
```scala
if (buffer.isEmpty) push(out, ...)
else completeStage()
```

2016-10-31 11:43 UTC, drewhk commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      if (isClosed(in)) {
why not factor out all `if (buffer.nonEmpty) push(out, buffer.dequeue())` calls to a single line as the first thing in the method, and then dispatch on `if(isClosed(in)) ... else if(!hasBeenPulled(in))`

2016-10-31 11:43 UTC, drewhk commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      else if (isAvailable(out)) onPull()
how can this happen? If the buffer is not empty, then `isAvailable(out)` cannot be true unless we were pulled and forgot to push a dequeued element.

2016-11-13 09:42 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +          push(out, buffer.dequeue())
`isAvailable(out)` can be true here when it has been pulled but there is no element in buffer to delivered. I have written some comments in the source file.

2016-11-13 09:43 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      if (isClosed(in)) {
Refactor as you suggested. Thanks:)

2016-11-13 09:44 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +      else if (isAvailable(out)) onPull()
You are right. Have deleted it .

2016-11-13 12:15 UTC, Hawstein commented
@drewhk  The PR is updated.

2016-11-14 13:26 UTC, drewhk commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +          push(out, buffer.dequeue())
> isAvailable(out) can be true here when it has been pulled but there is no element in buffer to delivered. I have written some comments in the source file.

Ok, but then there must have been a push() in-between, otherwise buffer.dequeue() would fail. But if there was a push, then that element should have been emitted, not buffered.

To put it shortly:
 - isAvailable(out) implies that there were a pull() before which was not answered
 - buffer.nonEmpty implies that there was a push() whose element has not been dequeued
 - but these two together are a contradiction

2016-11-14 13:37 UTC, Hawstein commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +          push(out, buffer.dequeue())
This is not a problem since I have updated the code:

```scala
    override def onPush(): Unit = {
       val elem = grab(in)
       // If out is available, then it has been pulled but no dequeued element has been delivered.
       // It means the buffer at this moment is definitely empty,
       // so we just push the current element to out, then pull.
       if (isAvailable(out)) {
         push(out, elem)
         pull(in)
       } else {
         enqueueAction(elem)
       }
     }
```

2016-11-14 13:43 UTC, drewhk approved these changes
LGTM

2016-11-14 13:50 UTC, Hawstein commented
Does the test will run automatically again? It failed because of the `pr-validation:test`, I think it does nothing to do with the unit tests.

2016-11-14 15:43 UTC, johanandren commented
PLS BUILD

2016-11-15 16:50 UTC, Hawstein commented
Can this PR be merged since there are 2 LGTM 😄

2016-11-15 17:48 UTC, johanandren commented
Thanks @Hawstein !

2016-11-15 17:48 UTC, merged