Fixes #20553 Tree flattening should be separate from Fusing
akka/akka pull request #21688
Opened 2016-10-17 21:05 UTC by kkasravi

2016-10-18 08:26 UTC, ktoso commented
OK TO TEST

2016-10-19 10:21 UTC, patriknw reviewed
looking good, let's see what @drewhk  says when he is back next week

2016-10-19 10:21 UTC, patriknw commented on akka-stream/src/main/scala/akka/stream/Fusing.scala
> +  def structuralInfo[S <: Shape, M](g: Graph[S, M], attributes: Attributes): StructuralInfoModule =
this should probably have an `INTERNAL API` marker in the docs, since `StructuralInfoModule` is in the `impl` package

2016-10-19 23:14 UTC, kkasravi commented on akka-stream/src/main/scala/akka/stream/Fusing.scala
> +  def structuralInfo[S <: Shape, M](g: Graph[S, M], attributes: Attributes): StructuralInfoModule =
Thanks @patriknw - I added the necessary filter in MiMa.scala for the internal type StructuralInfo which is now StructuralInfoModule. Hopefully this build will now pass.

2016-10-20 11:23 UTC, viktorklang commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Fusing.scala
> +        matValues.head._2,
Can `matValues` be guaranteed to be non-empty here?

2016-10-26 08:35 UTC, drewhk commented
LGTM, except the issue what @viktorklang found.

2016-10-27 14:44 UTC, kkasravi commented
@drewhk @viktorklang I'll fix today and push a new PR. Thanks!

2016-10-28 22:55 UTC, kkasravi commented
@drewhk, @viktorklang 

Hi - 

I did the following
```
    case object BogusModule extends AtomicModule {
      override def shape = ClosedShape
      override def replaceShape(s: Shape) =
        if (s != shape) throw new UnsupportedOperationException("cannot replace shape")
        else this

      override def compose(that: Module): Module = compose(that, scaladsl.Keep.left)

      override def compose[A, B, C](that: Module, f: (A, B) => C): Module = {
        if (f eq scaladsl.Keep.right) {
          that
        } else if (f eq scaladsl.Keep.left) {
          val mat =
          if (IgnorableMatValComp(that)) {
            Ignore
          } else {
            Transform(_ => NotUsed, that.materializedValueComputation)
          }
          CompositeModule(
            if (that.isSealed) Set(that) else that.subModules,
            that.shape,
            that.downstreams,
            that.upstreams,
            mat,
            if (this.isSealed) Attributes.none else attributes)
        } else {
          throw new UnsupportedOperationException(
            "It is invalid to combine materialized value with BogusModule " +
            "except with Keep.left or Keep.right")
        }
      }

      override def withAttributes(attributes: Attributes): Module =
        throw new UnsupportedOperationException("BogusModule cannot carry attributes")

      override def attributes = Attributes.none
      override def carbonCopy: Module = this
      override def isRunnable: Boolean = true
      override def isAtomic: Boolean = true
      override def materializedValueComputation: MaterializedValueNode = Ignore
    }

    RunnableGraph(BogusModule).run()
```

The matValues in BuildStructuralInfo.toInfo had a single entry  (BogusModule -> Copy of BogusModule). From my analysis - it's not possible to not have a matValues without an entry  (matValues.head can never be null).

However a scala.MatchError was thrown due to BogusModule not matching any type within ActorMaterializerImpl.materializeAtomic. This is probably ok IMO since BogusModule isn't extending Source, Sink, GraphStage, etc. Stack trace is below:

```
Exception in thread "main" scala.MatchError: BogusModule (of class org.apache.gearpump.akkastream.example.Test9$BogusModule$2$)
	at akka.stream.impl.ActorMaterializerImpl$$anon$2.materializeAtomic(ActorMaterializerImpl.scala:165)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:954)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:950)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:950)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:957)
	at akka.stream.impl.MaterializerSession$$anonfun$materializeModule$1.apply(StreamLayout.scala:950)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
	at akka.stream.impl.MaterializerSession.materializeModule(StreamLayout.scala:950)
	at akka.stream.impl.MaterializerSession.materialize(StreamLayout.scala:917)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:240)
	at akka.stream.impl.ActorMaterializerImpl.materialize(ActorMaterializerImpl.scala:138)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:350)
	at org.apache.gearpump.akkastream.example.Test9$.main(Test9.scala:107)
	at org.apache.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:42)
	at org.apache.gearpump.util.AkkaApp$$anonfun$main$1.apply(AkkaApp.scala:42)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.gearpump.util.AkkaApp$class.main(AkkaApp.scala:41)
	at org.apache.gearpump.akkastream.example.Test9$.main(Test9.scala:36)
	at org.apache.gearpump.akkastream.example.Test9.main(Test9.scala)
```

2016-10-31 11:10 UTC, drewhk commented
@kkasravi can you please add a test though that materializes an empty RunnableGraph? Just in case. Otherwise LGTM

2016-11-01 14:34 UTC, kkasravi commented
@drewhk thanks - will add the the empty RunnableGraph today and repush.

2016-11-07 14:13 UTC, drewhk requested changes
Test an actual empty graph instead of a synthetic module. Then this can be merged.

2016-11-07 14:13 UTC, drewhk commented on akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala
> +
Hm, I was actually thinking about trying this:

```scala
val g = GraphDSL.create { b =>
  ClosedShape
}
Fusing.aggressive(g)
```

2016-11-22 15:55 UTC, kkasravi commented on akka-stream-tests/src/test/scala/akka/stream/FusingSpec.scala
> +
Thanks @drewhk - sorry I missed this. I'll update the PR.

2016-11-23 09:03 UTC, drewhk approved these changes

2016-11-23 09:29 UTC, merged