+doc,per #21689 document calling persist() in Future is unsafe
akka/akka pull request #21699
Opened 2016-10-19 08:47 UTC by ktoso

Refs #21689 by adding more explicit docs about it.

2016-10-19 10:10 UTC, patriknw requested changes

2016-10-19 10:10 UTC, patriknw commented on akka-docs/rst/java/persistence.rst
> +  While it is possible to next ``persist`` calls within one another,
s/next/nest/

2016-10-19 10:10 UTC, patriknw commented on akka-docs/rst/java/persistence.rst
> +  it is *not* legal to nest ``persist`` calls in Futures! Doing so will break the
not really about nesting, it's simply not legal to call `persist` from a Future callback or any other thread than the actor's message processing thread

2016-10-19 16:28 UTC, johanandren approved these changes

2016-10-21 14:36 UTC, ktoso commented
Addressed all comments so merging.

2016-10-21 14:36 UTC, merged