improve streams actor integration docs, #21698
akka/akka pull request #21700
Opened 2016-10-19 09:25 UTC by patriknw

* mapAsync + ask should be the first choice
* add missing Source.queue
* prefer actorRefWithAck
* move ActorPublisher and ActorSubscriber to the end
  with additional warning

2016-10-19 09:26 UTC, patriknw commented
Refs #21698

2016-10-19 09:43 UTC, johanandren approved these changes
LGTM

2016-10-19 09:43 UTC, johanandren commented on akka-docs/rst/java/stream/stream-integrations.rst
> +stage and then actor is effectively a sink of the stream.
Maybe clarify that it is when you don't care but still want request-response to backpressure? I first read this and thought "why would I use ask if I don't care about the reply?".

2016-10-19 11:34 UTC, patriknw commented on akka-docs/rst/java/stream/stream-integrations.rst
> +stage and then actor is effectively a sink of the stream.
good point, fixed b0b7387

2016-10-19 13:14 UTC, johanandren commented on akka-docs/rst/java/stream/stream-integrations.rst
> +If you don't care about the reply values and only use them back-pressure signals you
"only use them _as_ back-pressure signals"

2016-10-19 13:23 UTC, ktoso commented on akka-docs/rst/java/stream/stream-integrations.rst
> +``SourceQueue.offer`` returns ``CompletionStage<StreamCallbackStatus<Boolean>>`` which completes with ``Success(true)``
The javadoc seems to be incorrect on those (!) - there is no `StreamCallbackStatus` in the entire project, it seems that `QueueOfferResult` is meant instead?

2016-10-19 13:32 UTC, ktoso commented on akka-docs/rst/java/stream/stream-integrations.rst
> +  :class:`ActorPublisher` and :class:`ActorSubscriber` will probably be deprecated in future versions of Akka.
good 👍

2016-10-19 13:33 UTC, ktoso requested changes
The non existing type needs to be fixed here ( https://github.com/akka/akka/pull/21700#discussion_r84068183 ) and in javadoc, otherwise very good improvement 👍

2016-10-24 10:16 UTC, drewhk approved these changes

2016-10-24 11:58 UTC, patriknw commented
@ktoso fixed the wrong `StreamCallbackStatus`, and found missing java api: 1a102f7

2016-10-26 08:23 UTC, ktoso approved these changes

2016-10-26 08:24 UTC, merged