Fix #21791 by adding a version override for scala.util.parser
akka/akka pull request #21835
Opened 2016-11-14 23:35 UTC by rovarga

This patch fixes akka-stream's OSGi manifest so it references
valid version of scala.util.parser.combinators, 1.0.4, instead
of the scala version we build for.

Signed-off-by: Robert Varga <nite@hq.sk>

2016-11-14 23:35 UTC, typesafehub-validator commented
Hi @rovarga,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2016-11-15 00:00 UTC, rovarga commented
For the record, resulting jar passes OSGi validation of https://git.opendaylight.org/gerrit/48334 in local testing.

2016-11-16 10:16 UTC, ktoso commented
OK TO TEST

2016-11-16 15:48 UTC, johanandren commented
Refs #21791

2016-11-16 15:49 UTC, johanandren commented
LGTM (with the caveat that I have no clue about OSGi)

2016-11-17 10:05 UTC, drewhk commented
Hm, but what does use scala.util.parsing here??

2016-11-17 10:15 UTC, drewhk requested changes
I don't see Akka Stream having this dependency at all: http://search.maven.org#artifactdetails|com.typesafe.akka|akka-stream_2.11|2.4.12|jar

2016-11-18 10:48 UTC, rovarga commented
It comes in transitively from:
http://search.maven.org/#artifactdetails|com.typesafe|ssl-config-core_2.11|0.2.1|jar

The import statement for that package should not be generated, but for some reason it is -- I honestly do not have a clue why and this is just a band-aid for it to have correct version.

2016-11-18 11:37 UTC, drewhk commented
Hm, shouldn't then ssl-config-core be fixed for OSGi? I have not much clue about OSGi just want to understand.

2016-11-18 13:02 UTC, rovarga commented
ssl-config-core's manifest is okay, it contains the proper import -- and akka-stream's manifest should not contain it at all.

After playing with this a bit more, it looks like it is a combination of scalaImport() and "*" in defaultImports(). Adding explicit exclusions for scala.compat.java8.* and scala.util.parsing.* before scalaImport() seems to produce a manifest which includes the import for compat.java8, but not for scala.util.parsing.combinators.

2016-11-25 15:17 UTC, patriknw commented
PLS BUILD

2016-11-25 15:19 UTC, patriknw reviewed
I have no clue, but if this is fixing something and you are sure that it is not breaking something else I can approve it.

2016-11-28 07:55 UTC, johanandren commented
Unrelated test failure

2016-11-28 08:04 UTC, johanandren commented
PLS BUILD

2016-12-06 14:38 UTC, drewhk approved these changes

2016-12-06 14:38 UTC, drewhk commented
will need a backport now to the 2.4 branch

2016-12-06 15:43 UTC, merged

2016-12-06 15:43 UTC, patriknw commented
Thanks @rovarga 
I'll backport to 2.4 branch