Adding debug message when passivate method cannot identify entity
akka/akka pull request #21886
Opened 2016-11-23 09:22 UTC by sebbes

Hopefully this will help others to see an unmatched entity when expecting the stopMessage to be sent back to the entity.

2016-11-28 10:09 UTC, johanandren commented on akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
> +      case _ ⇒ log.debug("Unknown entity. Not sending stopMessage back to entity.")
Maybe include the path of the `entity` as well?

2016-11-28 10:09 UTC, johanandren commented
OK TO TEST

2016-11-28 11:02 UTC, sebbes commented on akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
> +      case _ ⇒ log.debug("Unknown entity. Not sending stopMessage back to entity.")
yes, good idea. Will you add this?

2016-11-28 11:58 UTC, johanandren commented on akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
> +      case _ ⇒ log.debug("Unknown entity. Not sending stopMessage back to entity.")
If you cannot find time for it, sure.

2016-12-06 15:27 UTC, patriknw requested changes
@sebbes Can you please do the suggested changes and push to your branch. Apart from that it is looking good and we can merge.

2016-12-06 15:27 UTC, patriknw commented on akka-cluster-sharding/src/main/scala/akka/cluster/sharding/Shard.scala
> +      case _ ⇒ log.debug("Unknown entity. Not sending stopMessage back to entity.")
Perhaps even use different log messages for the two cases:
```scala
case Some(_) => log.debug("Passivation already in progress for {}. Not sending stopMessage back to entity.", entity)
case None => log.debug("Unknown entity {}. Not sending stopMessage back to entity.", entity)

```

2017-01-10 09:54 UTC, patriknw commented
@sebbes Will you be able to do the final adjustment, or shall I do it for you?

2017-01-23 09:42 UTC, sebbes commented
Hi Patrik,

Sorry for the late reply, was on leave. I will adjust it, will do so this
week.

Thanks,
Sebastian

On 10 January 2017 at 10:54, Patrik Nordwall <notifications@github.com>
wrote:

> @sebbes <https://github.com/sebbes> Will you be able to do the final
> adjustment, or shall I do it for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/akka/akka/pull/21886#issuecomment-271532705>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABRjmYwNz_4KgP9mXPKO2uJBWkUzuxquks5rQ1VZgaJpZM4K6XAA>
> .
>

2017-01-23 10:34 UTC, ktoso commented
You changed the None case, but a rewording was also proposed for the Some case, see @patriknw's comment :)

Please reword the Some log statement too: `case Some(_) => log.debug("Passivation already in progress for {}. Not sending stopMessage back to entity.", entity)`, after that LGTM

2017-01-23 12:19 UTC, johanandren approved these changes
LGTM

2017-02-10 11:02 UTC, drewhk approved these changes

2017-02-21 13:08 UTC, patriknw approved these changes
LGTM

2017-02-21 13:08 UTC, merged

2017-02-21 13:09 UTC, patriknw commented
Thanks @sebbes 
Sorry for long review time.

2017-02-21 13:35 UTC, sebbes commented
Hello Patrick,

You're welcome. Thank you for adding this; I am happy to use akka!!!

Regards,
Sebastian Näfe

On 21 February 2017 at 14:09, Patrik Nordwall <notifications@github.com>
wrote:

> Thanks @sebbes <https://github.com/sebbes>
> Sorry for long review time.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/akka/akka/pull/21886#issuecomment-281339895>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABRjmdJ5nwQCFTFfoAFb3VYiyxd7tsM7ks5reuIRgaJpZM4K6XAA>
> .
>