Remove static config path of levelDBJournal and localSnapshotStore
akka/akka pull request #21945
Opened 2016-12-05 05:10 UTC by ortigali

Refs #21394

2016-12-06 14:03 UTC, patriknw commented
OK TO TEST

2016-12-06 14:05 UTC, patriknw commented
This will probably require a binary compatibility check filter to be added at the end of project/MiMa.scala
You can see what to add by running `sbt mimaReportBinaryIssues`

2016-12-06 14:14 UTC, patriknw requested changes
looking good, but perhaps try the constructor alternative

2016-12-06 14:14 UTC, patriknw commented on akka-persistence/src/main/scala/akka/persistence/journal/leveldb/LeveldbStore.scala
> +  val config = transformConfig(Persistence(context.system).configFor(self))
I see that we use this in `AsyncWriteJournal` and it's not wrong, but I think the prescribed approach is to have it as a constructor parameter. See https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L39

2016-12-06 14:14 UTC, patriknw commented on akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
> +    max-load-attempts = 3
was it required to add those properties?

2016-12-07 06:19 UTC, ortigali commented on akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
> +    max-load-attempts = 3
new config path do not fallback with "akka.persistence.journal.leveldb". So user should set requirement parameters. Or should it fallback with defaults?

2016-12-07 08:25 UTC, patriknw commented on akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
> +    max-load-attempts = 3
ok, then I understand. Yes it's correct to specify them.
Can also be done with:

```
akka.persistence.snapshot-store.local-delete-fail = ${akka.persistence.snapshot-store.local}
akka.persistence.snapshot-store.local-delete-fail {
  class = "akka.persistence.SnapshotFailureRobustnessSpec$DeleteFailingLocalSnapshotStore"
  dir = "target/snapshots-SnapshotFailureRobustnessSpec/"
}
```

2016-12-07 08:40 UTC, ortigali commented on akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
> +    max-load-attempts = 3
_max-load-attempts_ is a required key. If we do not mention it, config throws 
`com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'max-load-attempts'` 
other keys are also required. User must specify them if they want different config path

2016-12-07 10:09 UTC, ortigali commented on akka-persistence/src/test/scala/akka/persistence/SnapshotFailureRobustnessSpec.scala
> +    max-load-attempts = 3
ok, i understand now

2016-12-07 18:21 UTC, ortigali commented on akka-persistence/src/test/scala/akka/persistence/EndToEndEventAdapterSpec.scala
> +        EventFilter[ActorInitializationException](occurrences = 1, pattern = ".*akka.persistence.journal.leveldb.*") intercept {
LeveldbJournal constructor takes config parameter, and reflection uses Constructor.newInstance method to instantiate it.
[ Constructor.newInstance() always wraps the thrown exception with an InvocationTargetException.](https://docs.oracle.com/javase/tutorial/reflect/member/ctorInstance.html)

so ActorInitializationException message is changed

2016-12-09 12:52 UTC, patriknw commented on akka-persistence/src/test/scala/akka/persistence/EndToEndEventAdapterSpec.scala
> +        EventFilter[ActorInitializationException](occurrences = 1, pattern = ".*akka.persistence.journal.leveldb.*") intercept {
hm, should we unwrap InvocationTargetException since that is not very useful for anyone?

2016-12-12 14:00 UTC, patriknw approved these changes
LGTM

2016-12-12 14:00 UTC, patriknw commented
@ortigali thanks !

2016-12-13 13:02 UTC, johanandren approved these changes
LGTM, thanks!

2016-12-13 13:04 UTC, merged