Separate AbstractPersistentActors for 2.11 and 2.12
akka/akka pull request #22251
Opened 2017-02-02 21:50 UTC by johanandren

to avoid the SAM problem in Java from Scala 2.12 builds of Akka.

Still has the problem that `BoxedUnit` in `Function1<A,scala.runtime.BoxedUnit>` cannot really be created from a procedure in Java (returning `void`)

2017-02-02 22:13 UTC, johanandren commented
Y U NO TRUST ME ANYMORE JENKINS!?!  (╯°□°）╯︵ ┻━┻

2017-02-04 00:27 UTC, johanandren commented
After a discussion with the Scala-team it seems we cannot really solve this problem this way, or any other way without breaking binary compatibility. So we likely will have to provide different names for persist and persistAll for Java.

2017-02-04 00:56 UTC, johanandren commented
Solution after try 26 to solve this with the joint effort of the Scala and Akka team: For 2.12 we pull the Scala `persist` and `persistAll` into `PersistentActor`, add the Java versions of the methods `AbstractPersistentActor` and change it to directly inherit `EventSourced`.

This will break binary compatibility for 2.5_2.12 persistent actors but we decided it is not common that libraries extend persistent actor and that it therefore is worth it.

2017-02-06 02:38 UTC, patriknw requested changes

2017-02-06 02:38 UTC, patriknw commented on akka-persistence/build.sbt
> +  file((sourceDirectory in Compile).value.absolutePath + "/scala-" + scalaVersion.value.dropRight(2))
I thought sbt did this automatically? 
How does `dropRight(2)` work for both `2.11.10` and `2.12.1`?

2017-02-06 02:38 UTC, patriknw commented on akka-persistence/src/main/scala-2.11/akka/persistence/AbstractPersistentActor.scala
> + * Scala 2.11 API version
That should not really be shown in JavaDoc

2017-02-06 02:38 UTC, patriknw commented on akka-persistence/src/main/scala-2.12/akka/persistence/AbstractPersistentActor.scala
> +abstract class AbstractPersistentActor extends AbstractActor with PersistentActor with Eventsourced {
This is not what we discussed and what you described.
For 2.12 we must:
* move the scala api `persist` methods to `PersistentActor` from `EventSourced`
* `AbstractPersistentActor extends AbstractActor with Eventsourced`

This probably means that we must have duplicate sources for AbstractPersistentActor, PersistentActor, Eventsourced.

We could get away with less duplication if we break binary compatibility for 2.11 also. Then we would not any version specific sourced at all, right? Tempting?

Do we have anything else extending `PersistentActor`? `AtLeastOnceDelivery`?

2017-02-06 08:28 UTC, johanandren commented
@patriknw This was the first try, before we had the final discussions, so please ignore for now.

2017-02-07 13:53 UTC, johanandren commented
Now it can be unignored ;)

Refs #22218

2017-02-10 10:14 UTC, drewhk commented
This is source compatible though, right?

2017-02-10 10:24 UTC, patriknw commented
yes, it's source compatible

2017-02-14 09:04 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
>  trait PersistentActor extends Eventsourced with PersistenceIdentity {
Should probably add a Scala API: here

2017-02-14 09:05 UTC, johanandren commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +were based on). T
ups linefeed weirdness

2017-02-14 09:05 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
> +trait AtLeastOnceDelivery extends PersistentActor with AtLeastOnceDeliveryLike {
Should add Scala API: here as well

2017-02-14 09:07 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
> +abstract class AbstractPersistentActor extends AbstractActor with Eventsourced {
I think its missing the receive = receiveCommand

2017-02-14 09:08 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
> +abstract class AbstractPersistentActor extends AbstractActor with Eventsourced {
Which should indicate that there is no test coverage for the Java API, I'll look into that as well.

2017-02-14 09:11 UTC, patriknw approved these changes
LGTM, after minor cleanup

2017-02-14 09:11 UTC, patriknw commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +his means that the Akka 2.5 artifact cannot be a class path drop in replacement of Akka 2.4 and earlierif you use
strange line break

2017-02-14 09:11 UTC, patriknw commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +his means that the Akka 2.5 artifact cannot be a class path drop in replacement of Akka 2.4 and earlierif you use
earlierif

2017-02-14 09:11 UTC, patriknw commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +his means that the Akka 2.5 artifact cannot be a class path drop in replacement of Akka 2.4 and earlierif you use
I don't think you have to mention earlier because persistence was experimental in 2.3 and changed

2017-02-14 09:42 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/PersistentActor.scala
> +abstract class AbstractPersistentActor extends AbstractActor with Eventsourced {
Ah, it was already in there.

2017-02-14 10:57 UTC, ktoso commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +version of Akka.
good

2017-02-17 11:28 UTC, ktoso commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +To be able to evolve the Java APIs of ``PersistentActor`` and ``AtLeastOneDelivery`` to work with Scala 2.12
call them the Java names here? `AbstractPersistentActor`

2017-02-17 11:28 UTC, ktoso commented on akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
> +   * Internal API
Call me OCD but INTERNAL API

2017-02-17 11:28 UTC, ktoso commented on akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
> +trait AtLeastOnceDelivery extends PersistentActor with AtLeastOnceDeliveryLike {
I'm confused, what is the Java API for it now?

2017-02-17 15:45 UTC, johanandren commented on akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala
> +trait AtLeastOnceDelivery extends PersistentActor with AtLeastOnceDeliveryLike {
`AbstractPersistentActorWithAtLeastOnceDelivery` (short and concise...)

2017-02-20 11:25 UTC, patriknw commented
@johanandren I think you can squash and merge this.

2017-02-20 11:25 UTC, patriknw commented
PLS BUILD

2017-02-20 13:50 UTC, merged