22295 Allow user define what is failure in terms on circuit breaker
akka/akka pull request #22298
Opened 2017-02-13 12:35 UTC by buaya91

This PR is to address #22295 

I overloaded `withCircuitBreaker` and it's siblings with an additional argument which allow user to specify what result should increase failure count and what should not.

Default behaviour is not changed, thus should be backward compatible

2017-02-14 13:29 UTC, jrudolph commented
OK TO TEST

2017-02-19 22:26 UTC, buaya91 commented
Hi, @jrudolph 

The CI have been in pending state for almost a week, do you know why is that so?

2017-02-20 08:28 UTC, jrudolph commented
PLS BUILD

2017-02-20 08:28 UTC, jrudolph commented
@buaya91 it seems to hang from time to time.

2017-02-21 11:32 UTC, patriknw requested changes
The Java API would need some more thought.
Reverting the formatting changes would simplify reviewing.

2017-02-21 11:32 UTC, patriknw commented on akka-actor-tests/src/test/scala/akka/pattern/CircuitBreakerSpec.scala
> +        breaker().withSyncCircuitBreaker(2, CircuitBreakerSpec.evenNumberIsFailure)
Here is a good example of where it was difficult to solve without this feature. 
Triggering failure in the CB but still return `2` from the call.

2017-02-21 11:32 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailure[T]: Try[T] ⇒ Boolean = {
this can be a `val`

2017-02-21 11:32 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailure[T]: Try[T] ⇒ Boolean = {
what would be the corresponding thing for `Java API`?

2017-02-21 11:32 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +      newState)
these re-formatting make it difficult to review, and I can't say that this reads better

2017-02-21 11:32 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +    defineFailureFn: Try[T] ⇒ Boolean): CompletionStage[T] =
Java API should use `java.util.Function`, and `Try` is rather alien in Java API. Not sure what we shall use?

2017-02-21 11:32 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +      }),
DRY?
```
withSyncCircuitBreaker(body, CircuitBreaker.exceptionAsFailure)
```

2017-02-21 19:35 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +      newState)
Sorry, my bad, I will revert

2017-02-21 20:41 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailure[T]: Try[T] ⇒ Boolean = {
Great question, do you a BiFunction would cut it?

I ain't familiar with Java, but seems CompletionStage can be handle by a Bifunction according to [docs](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html#handle-java.util.function.BiFunction-)

We can allow user to pass a BiFunction which return boolean

2017-02-22 10:30 UTC, buaya91 commented
@patriknw @jrudolph 

This changes did not pass binary compatibility, I presume because I've added new methods?
And it should be harmless, correct me if I am wrong

2017-02-22 10:38 UTC, jrudolph commented
The failures are:

```
[info] akka-actor: found 2 potential binary incompatibilities while checking against com.typesafe.akka:akka-actor_2.11:2.4.10  (filtered 50)
[error]  * method callThrough(scala.Function0,scala.Function1)scala.concurrent.Future in trait akka.pattern.CircuitBreaker#State is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.callThrough")
[error]  * method invoke(scala.Function0,scala.Function1)scala.concurrent.Future in trait akka.pattern.CircuitBreaker#State is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.invoke")
```

So, as long as there are no custom implementations of `CircuitBreaker` / `CircuitBreaker.State` it may be ok.

2017-02-22 10:59 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailure[T]: Try[T] ⇒ Boolean = {
`BiFunction` is like `scala.Function2`, i.e. 2 parameters. Question is how we should represent `Try`? As two `Optional`? `BiFunction[Optional[T], Optional[Throwable]]`?

Perhaps we can use `akka.actor.Status` to represent the `Try` in the Java API. It has `Sucess` and `Failure` that are consumable from Java.

2017-02-22 19:09 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailure[T]: Try[T] ⇒ Boolean = {
I think simply 

`Bifunction<T, Throwable, Boolean> will do?`

As it's java, the user should be aware to catch null if they expect null

2017-02-22 21:58 UTC, buaya91 commented
@patriknw 
After trying to implement for java api, I think your suggestion is closer to what we want, I will present the problem here and look for suggestion from anyone.

Problem: Provide java api to determine whether circuit breaker should increase failure count or not, I have 3 possible solution so far.

a) accept a `BiFunction[Optional[T], Optional[Throwable], Boolean]`
   - Pro: Relatively Typesafe and easy interop with CompletionStage
   - Con: It does not suggest the function only take either a T or a Throwable, but never both

b) accept a `akka.actor.Status`
   - Pro: This provide semantic of either `Success` or `Failure`
   - Con: `Success` takes in `Any`, thus lose some typesafety

c) Implement another `Status` like ADT which Success is Generic instead of taking Any
   - Pro: Provide all we need
   - Con: Not sure if it worth it to add yet another class for such limited use case

d) accept a `java.util.function.Function[T, Boolean]`, we will expect user to do try catch inside the function if he want to handle error case
   - Pro: Might be more familiar with java user? also provide typesafety
   - Con: Does not expose the fact that it can throws

Personally I prefer **a** and **d** , looking for feedback or comments on this, especially people that uses java more

2017-02-23 12:33 UTC, patriknw commented
I have indeed seen d) in some other Java API and found it so ugly. I vote for **b)**

2017-02-23 13:02 UTC, buaya91 commented
@patriknw 

is losing type-safety ok?

something like this

```
def rpc():Callable[CompletionStage[String]]
def defineFailure(status: akka.actor.Status): Boolean = {
   if (status.isInstanceOf[Success])
      status.asInstanceOf[Success].value == 2
   else
      false
}

callWithCircuitBreakerCS(rpc, defineFailure)

// rpc always return a String, but the defineFailure check on Int
```

this will compile


Anyway, I will implement 5 hours later, I shall see if we have better alternatives, if not I'll go with @patriknw 

Cheers

2017-02-23 13:14 UTC, patriknw commented
@buaya91 yeah, perhaps not so nice, and we can use create a small class instead like:

```scala
class CallResult[T](success: T, failure: Throwable) {
  def isSuccess: Boolean = success != null
  def getSuccess: T = 
    if (isSuccess) success
    else throw new NoSuchElementException("No value present")
  
  // TODO similar for the failure
}
```

2017-02-23 19:42 UTC, buaya91 commented
@patriknw After some more thought, I think introducing another class is not the way, we will effectively implement yet another `Try`, albeit less powerful, so I went with option a)

Hope this will work.

2017-03-03 15:30 UTC, buaya91 commented
@jrudolph could you restart the pipeline again?
@patriknw any feedback on this?

cheers

2017-03-15 10:06 UTC, patriknw requested changes
this looks good, with one small naming question

2017-03-15 10:06 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailureJava[T]: BiFunction[Optional[T], Optional[Throwable], java.lang.Boolean] =
that naming is rather ugly, is this needed as public API?

2017-03-15 10:06 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  val exceptionAsFailure: Try[_] ⇒ Boolean = {
is this needed as public API?

2017-03-15 10:07 UTC, patriknw commented
PLS BUILD

2017-03-15 10:51 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  val exceptionAsFailure: Try[_] ⇒ Boolean = {
You're right, I will change it to private

2017-03-15 10:52 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  def exceptionAsFailureJava[T]: BiFunction[Optional[T], Optional[Throwable], java.lang.Boolean] =
You're right, I will change it to private

2017-03-15 11:07 UTC, buaya91 commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  val exceptionAsFailure: Try[_] ⇒ Boolean = {
By the way, any suggestions of the name?

2017-03-15 11:18 UTC, patriknw commented on akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala
> +  val exceptionAsFailure: Try[_] ⇒ Boolean = {
If it's private I think the name is fine

2017-03-16 10:10 UTC, patriknw commented
@buaya91 binary compatibility check failed:
```
[error]  * method callThrough(scala.Function0,scala.Function1)scala.concurrent.Future in trait akka.pattern.CircuitBreaker#State is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.callThrough")
[error]  * method invoke(scala.Function0,scala.Function1)scala.concurrent.Future in trait akka.pattern.CircuitBreaker#State is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.invoke")
```

That's all internal, so it's safe to add the filters. Please add the following to project/MiMa.scala in the section `bcIssuesBetween24and25`:

```
ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.callThrough"),
ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.pattern.CircuitBreaker#State.invoke"),
```

Somewhere here: https://github.com/akka/akka/blob/master/project/MiMa.scala#L105

2017-03-16 19:39 UTC, patriknw commented
I rebased this and opened https://github.com/akka/akka/pull/22586

2017-03-16 19:39 UTC, closed without merging