Suggest using 64bit JVM for Artery in docs
akka/akka pull request #22313
Opened 2017-02-14 12:53 UTC by andrievskya

https://github.com/akka/akka/issues/22303

2017-02-14 12:53 UTC, typesafehub-validator commented
Hi @andrievskya,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2017-02-14 13:04 UTC, andrievskya commented
Signed the Typesafe CLA

2017-02-14 13:35 UTC, johanandren reviewed
Thanks. Did you try it on 32bit and have problems? (It never even surfaced to me that people might be using 32bit JVMs)

2017-02-14 13:35 UTC, johanandren commented on akka-docs/rst/java/remoting-artery.rst
> +  Aeron requires 64bit JVM for reliable work.
"to work reliably"

2017-02-14 13:36 UTC, johanandren commented
NVM question about 32bit, saw ticket now.

2017-02-14 15:56 UTC, drewhk approved these changes
Small changes to wording required

2017-02-14 15:56 UTC, drewhk commented on akka-docs/rst/java/remoting-artery.rst
> +  Aeron requires 64bit JVM for reliable work.
+1

2017-02-15 05:24 UTC, andrievskya commented on akka-docs/rst/java/remoting-artery.rst
> +  Aeron requires 64bit JVM for reliable work.
yes, that sounds better

2017-02-15 10:59 UTC, patriknw requested changes

2017-02-15 10:59 UTC, patriknw commented on akka-docs/rst/java/remoting-artery.rst
> +  Aeron requires 64bit JVM for reliable work.
same thing in `scala/remoting-artery.rst`

not sure that this deserves `warning` (red box). I think `note` is enough. 64 bit is default in most environments

2017-02-17 13:17 UTC, patriknw commented
@andrievskya Thanks for adding this. We have different pages for java and scala. Can you please add the same thing to `akka-docs/rst/scala/remoting-artery.rst`. Then we can merge this.

2017-02-17 13:35 UTC, andrievskya commented
Added the same text to file you mentioned. Do I need to create another pull request, or something, so you can integrate changes into where you need, and I can close the issue?

2017-02-17 15:20 UTC, johanandren commented
Just commit and push to your github repo and they will appear in this PR.

2017-02-20 08:27 UTC, andrievskya commented
Added the same text to file you mentioned. Do I need to create another pull request, or something, so you can integrate changes into where you need, and I can close the issue?

2017-03-14 10:32 UTC, patriknw commented
@andrievskya would you like to complete this, or shall I do the copy?

2017-03-14 11:23 UTC, andrievskya commented
Do you mean closing pull request? or there are some meaningfull work left for me to do?

2017-03-14 11:46 UTC, patriknw commented
The remaining, that we are waiting for:

> We have different pages for java and scala. Can you please add the same thing to akka-docs/rst/scala/remoting-artery.rst.

2017-03-14 12:01 UTC, andrievskya commented
These changes are in commit 669543c9ee0699c149755a1f67b45603bb58862d in fork andrievskyaa/akka
(https://github.com/andrievskya/akka/commit/669543c9ee0699c149755a1f67b45603bb58862d) what do I need to do to put these changes where you need them?

2017-03-14 12:05 UTC, patriknw commented
Ok, push to the branch you used for this PR and they will show up here. Thanks. If trouble, just create a new PR.

2017-03-14 12:19 UTC, andrievskya commented
Created new pull request #22553 that (I hope) contains all the changes discussed here

2017-03-14 12:32 UTC, closed without merging