add case for DeathPactException stopping actor
akka/akka pull request #22328
Opened 2017-02-15 18:31 UTC by prettynatty

See https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/FaultHandling.scala#L155

2017-02-15 19:41 UTC, ktoso commented
OK TO TEST

2017-02-16 13:05 UTC, johanandren approved these changes

2017-02-17 12:49 UTC, patriknw requested changes

2017-02-17 12:49 UTC, patriknw commented on akka-docs/rst/java/fault-tolerance.rst
> +* ``DeathPactException`` will stop the failing child actor
same thing in akka-docs/rst/scala/fault-tolerance.rst

2017-02-17 23:31 UTC, prettynatty commented on akka-docs/rst/java/fault-tolerance.rst
> +* ``DeathPactException`` will stop the failing child actor
done

2017-02-20 09:56 UTC, patriknw approved these changes
LGTM, thanks

2017-02-20 09:57 UTC, merged