Schedule timer for remaining delayed elements #22416
akka/akka pull request #22417
Opened 2017-02-28 21:33 UTC by moatra

Schedules the timer for any remaining elements after a group of elements have been pulled down. Fixes #22416

2017-02-28 21:33 UTC, typesafehub-validator commented
Hi @talton-rmn,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2017-03-03 21:03 UTC, talton-rmn commented
CLA has made it through legal and been signed.

2017-03-14 13:40 UTC, 2m requested changes
Looks good.

2017-03-14 13:40 UTC, 2m commented on akka-stream/src/main/scala/akka/stream/impl/fusing/Ops.scala
> +          scheduleOnce(timerName, Math.max(10, waitTime).millis)
This is now the second place where the constant `10` is used. Please factor it out to a `final val DelayPrecisionMs = 10`

2017-03-30 09:49 UTC, johanandren approved these changes
LGTM

2017-03-30 11:41 UTC, 2m approved these changes

2017-03-30 14:27 UTC, merged