Allow multiple Cluster JMX MBeans in the same JVM
akka/akka pull request #22484
Opened 2017-03-07 16:22 UTC by richard-imaoka

Refs #18872 

I didn't want to change the default behavior which impacts existing users ... so add a new flag in config.

`akka.cluster.jmx.multi-mbeans-in-same-jvm = on` in config allows you register multiple Cluster JMX MBeans in the same JVM. It is `= off` by default, which preserves the old behavior. 

`jmx-client/akka-cluster` is also updated. When `akka.cluster.jmx.multi-mbeans-in-same-jvm = off` on the server (cluster) side, no change in behavior. If that is `= off`, you need to pass the `-p` optional parameter.

## manual tests:

### akka.cluster.jmx.multi-mbeans-in-same-jvm = off, on the server (cluster) side

* akka-cluster works same way as before

```
$ ./akka-cluster 127.0.0.1 9999 member-status
This jmx-client/akka-cluster tool is deprecated use curl and https://github.com/akka/akka-cluster-management instead, since 2.5.0.
Querying member status for 127.0.0.1
Up
```

### akka.cluster.jmx.multi-mbeans-in-same-jvm = on, on the server (cluster) side

* it doesn't work if you are missing -p

```
$ ./akka-cluster 127.0.0.1 9999 member-status
This jmx-client/akka-cluster tool is deprecated use curl and https://github.com/akka/akka-cluster-management instead, since 2.5.0.
Akka cluster MBean is not available on 127.0.0.1:9999 with MBean name 'akka:type=Cluster'
```

* -p needs to be passed

```
$ ./akka-cluster 127.0.0.1 9999 -p 2552 down akka.tcp://ClusterSystem@127.0.0.1:2551
This jmx-client/akka-cluster tool is deprecated use curl and https://github.com/akka/akka-cluster-management instead, since 2.5.0.
Marking akka.tcp://ClusterSystem@127.0.0.1:2551 as DOWN
```

* port 2551 is expected unavailable, as it was made DOWN above

```
$ ./akka-cluster 127.0.0.1 9999 -p 2551 member-status
This jmx-client/akka-cluster tool is deprecated use curl and https://github.com/akka/akka-cluster-management instead, since 2.5.0.
Akka cluster MBean is not available on 127.0.0.1:9999 with MBean name 'akka:type=Cluster,port=2551'
```

* but port 2552 is still available

```
$ ./akka-cluster 127.0.0.1 9999 -p 2552 cluster-status
This jmx-client/akka-cluster tool is deprecated use curl and https://github.com/akka/akka-cluster-management instead, since 2.5.0.
{
  "members": [
    {
      "address": "akka.tcp://ClusterSystem@127.0.0.1:2552",
      "roles": [],
      "status": "Up"
    },
    {
      "address": "akka.tcp://ClusterSystem@127.0.0.1:57642",
      "roles": [],
      "status": "Up"
    }
  ],
  "self-address": "akka.tcp://ClusterSystem@127.0.0.1:2552",
  "unreachable": []
}
```

2017-03-13 16:44 UTC, 2m requested changes
In general this looks great! As this adds support for multiple clusters running on one JVM it should also handle the case where separate clusters are listening on the same port but different hostname. This could be the case on nodes with multiple NICs.

2017-03-13 16:44 UTC, 2m commented on akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
> +  val JmxMultiMbeansInSameEnabled: Boolean = cc.getBoolean("jmx.multi-mbeans-in-same-jvm ")
Remove superfluous space at the end.

2017-03-14 10:45 UTC, patriknw requested changes
Looking very good. I think the only needed change is the whitespace. @2m has a valid point with multiple NICs, but in practice I guess that combination is rare and not worth spending time on.

2017-03-14 10:45 UTC, patriknw commented on akka-cluster/src/main/scala/akka/cluster/ClusterJmx.scala
> +              "If you are running multiple clusters in the same JVM, set 'akka.cluster.jmx.multi-mbeans-in-same-jvm = on' in config")
good

2017-03-14 10:45 UTC, patriknw commented on akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
> +  val JmxMultiMbeansInSameEnabled: Boolean = cc.getBoolean("jmx.multi-mbeans-in-same-jvm ")
yes, better fix this

2017-03-14 10:57 UTC, richard-imaoka commented on akka-cluster/src/main/scala/akka/cluster/ClusterSettings.scala
> +  val JmxMultiMbeansInSameEnabled: Boolean = cc.getBoolean("jmx.multi-mbeans-in-same-jvm ")
Hi yes, sorry I overlooked this but now fixed it in the latest commit.

2017-03-14 12:07 UTC, 2m approved these changes

2017-03-14 12:37 UTC, patriknw approved these changes
LGTM

2017-03-14 13:31 UTC, merged

2017-03-14 13:32 UTC, patriknw commented
Great work @richard-imaoka