Wip deprecate auto fusing setting johanandren
akka/akka pull request #22531
Opened 2017-03-10 18:48 UTC by johanandren

Refs #22431

2017-03-13 09:51 UTC, patriknw requested changes

2017-03-13 09:51 UTC, patriknw commented on akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
> +    _logger.info("Deprecated setting auto-fusing set to false. Since Akka 2.5.0 it does not have any effect " +
I think we have used `warning` level for such log messages in other places

2017-03-13 11:38 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/impl/PhasedFusingActorMaterializer.scala
> +    _logger.info("Deprecated setting auto-fusing set to false. Since Akka 2.5.0 it does not have any effect " +
+1 for warning level, LGTM otherwise

2017-03-13 11:38 UTC, ktoso approved these changes

2017-03-13 16:04 UTC, 2m requested changes
LGTM modulus small doc improvement.

2017-03-13 16:04 UTC, 2m commented on akka-docs/rst/project/migration-guide-2.4.x-2.5.x.rst
> +so this setting does not have any effect any more and has been deprecated. Running each stage in a stream can be done
Missing a note about running stages on separate actors.

> ... running each statge in a stream *on a separate actor* can be done ...

2017-03-14 14:08 UTC, 2m approved these changes

2017-03-15 08:15 UTC, merged