Little doc improvement due to issue #22566
akka/akka pull request #22591
Opened 2017-03-17 08:31 UTC by jjlopezm

This PR add to doc two params that are neccessary to start an akka cluster using remoting with ssl.
The related issue is :  https://github.com/akka/akka/issues/22566

2017-03-17 08:31 UTC, typesafehub-validator commented
Hi @jjlopezm,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2017-03-17 08:53 UTC, jjlopezm commented
I just sign the CLA :)

2017-03-20 15:54 UTC, johanandren approved these changes
LGTM, thanks!

2017-03-28 08:09 UTC, patriknw requested changes

2017-03-28 08:09 UTC, patriknw commented on akka-docs/rst/java/remoting.rst
> +        hostname = "127.0.0.1"
I'm not sure this is correct. Shouldn't it be in the `netty.ssl {` section?

2017-03-28 21:22 UTC, jjlopezm commented on akka-docs/rst/java/remoting.rst
> +        hostname = "127.0.0.1"
You're totally right. I'm going to change it.

2017-04-24 08:46 UTC, raboof commented
LGTM (but needs conflict resolution)

2017-04-24 09:26 UTC, ktoso commented
Resolved the conflicts, was very simple. LGTM

2017-04-24 09:26 UTC, ktoso approved these changes

2017-04-24 09:35 UTC, merged

2017-04-24 09:38 UTC, jjlopezm commented
Thanks! 👍

2017-04-24 09:45 UTC, raboof commented
Thank YOU! :)