#22662 Partial Function for onSignal
akka/akka pull request #22798
Opened 2017-04-26 14:14 UTC by 2m

This is only refactoring. I did not add any logic for making sure [this](https://github.com/akka/akka/issues/22662#issuecomment-290657402) still works. All tests pass, so either that is handled already or there are missing tests.

Fixes #22662

2017-04-26 15:31 UTC, patriknw requested changes
I think this is looking good, some comments...

2017-04-26 15:31 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +  }
change `MutableBehavior.onSignal`  also, but that should be something like:
```scala
def onSignal: PartialFunction[Signal, Behavior[T]] = PartialFunction.empty
```

2017-04-26 15:31 UTC, patriknw commented on akka-typed-tests/src/test/scala/akka/typed/scaladsl/adapter/AdapterSpec.scala
> +    Immutable[String] {
it's a bit sad that the type annotation is needed when `onSignal` is used, but the other syntax was not beutiful

2017-04-27 14:30 UTC, johanandren commented on akka-typed-tests/src/test/scala/akka/typed/scaladsl/adapter/AdapterSpec.scala
> +    Immutable[String] {
I don't get why that changes by calling a method on the returned object?

2017-04-27 14:45 UTC, patriknw commented on akka-typed-tests/src/test/scala/akka/typed/scaladsl/adapter/AdapterSpec.scala
> +    Immutable[String] {
some type inference is lost, but I don't know exactly why.
javac had same problem when I tried same thing in javadsl (and there this was a showstopper, see my other PR)

2017-04-28 08:08 UTC, patriknw approved these changes
LGTM, let's merge this first and I will rebase my PRs

2017-04-28 08:43 UTC, johanandren commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +  }
What about the Java API signal handling?

2017-04-28 08:43 UTC, johanandren approved these changes
LGTM

2017-04-28 08:51 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +  }
For the immutable see my comment here: https://github.com/akka/akka/pull/22798#discussion_r113715029

For the mutable we might want to do something when adding the builders, cc @raboof

2017-04-28 10:48 UTC, merged