Custom frame size computation support in Framing #22129
akka/akka pull request #22837
Opened 2017-05-03 16:09 UTC by manonthegithub

Framing did not supported custom frame size computation depending on header bytes.
For example different headers can assume static footers of different length that are not included in length field.
PR adds support for this scenario.

Refs #22129

2017-05-04 03:15 UTC, ktoso commented
OK TO TEST

2017-05-04 09:23 UTC, manonthegithub commented
All tests passed (0 failed).
Hey guys, I can't figure out what's wrong with pr validation?

2017-05-04 09:25 UTC, manonthegithub commented
Oh, I got it! Something wrong with binary compat.

2017-05-08 07:29 UTC, johanandren reviewed
Some minor doc language nitpicking, looks good!

2017-05-08 07:29 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +   * a truncated frame.
This sentence is unfinished or just strange.

2017-05-08 07:29 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +   *                         ''Actual frame size'' must be equal or bigger than sum of `fieldOffset` and `fieldLength`.
`in _a_ special fashion`, "have _a_ shape like this", "compute _the_ frame size".

"actual frame size must be equal ...", please clarify what happens if not, does the stage fail?

2017-05-08 10:32 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +   * a truncated frame.
I guess it lacks comma`... frame has been fully decoded _,_ this Flow will fail the ...`.
What do you mean about strangeness?
This is just copy from existing method.

2017-05-08 10:52 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +   *                         ''Actual frame size'' must be equal or bigger than sum of `fieldOffset` and `fieldLength`.
made changes as you asked)

2017-05-08 11:28 UTC, johanandren reviewed
One more thing before it is done as far as I can see.

2017-05-08 11:28 UTC, johanandren commented on akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
> +    computeFrameSize:       Option[(Array[Byte], Int) ⇒ Int]) extends GraphStage[FlowShape[ByteString, ByteString]] {
Always having a function, and providing a cached (in the companion object) default `(_, n) => n` is better as it avoids the allocation of two lambdas when applying the function and then the `getOrElse` below. Alternatively, do not `map` but use a pattern match on the option instead (which desugars into `if-else`s).

2017-05-08 12:31 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
> +    computeFrameSize:       Option[(Array[Byte], Int) ⇒ Int]) extends GraphStage[FlowShape[ByteString, ByteString]] {
I think, pattern match is better, it makes code more readable and you don't need to keep cache.

2017-05-08 12:31 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/scaladsl/Framing.scala
> +    computeFrameSize:       Option[(Array[Byte], Int) ⇒ Int]) extends GraphStage[FlowShape[ByteString, ByteString]] {
thanks for advice)

2017-05-08 12:34 UTC, johanandren approved these changes
Thanks, LGTM!

2017-05-08 14:43 UTC, johanandren commented
PLS BUILD

2017-06-27 07:04 UTC, patriknw commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    computeFrameSize:   akka.japi.function.Function2[Array[Byte], Int, Int]): Flow[ByteString, ByteString, NotUsed] =
as noticed by @ktoso these `Int` types must be `Integer` in javadsl

2017-06-27 10:26 UTC, manonthegithub commented
sorry... included something wrong in commit, ill fix

2017-06-27 11:49 UTC, johanandren commented on akka-stream-tests/src/test/scala/akka/stream/scaladsl/TickSourceSpec.scala
> +    "tiiickkk" in {
this wasn't meant to be pushed, right?

2017-06-27 11:50 UTC, johanandren commented on akka-testkit/src/main/scala/akka/testkit/TestKit.scala
> +    }
Nor this

2017-06-27 12:24 UTC, manonthegithub commented on akka-stream-tests/src/test/scala/akka/stream/scaladsl/TickSourceSpec.scala
> +    "tiiickkk" in {
i've removed it in the following commit d6010c3

2017-06-27 12:24 UTC, manonthegithub commented on akka-testkit/src/main/scala/akka/testkit/TestKit.scala
> +    }
i've removed it in the following commit d6010c3

2017-06-27 12:55 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    computeFrameSize:   akka.japi.function.Function2[Array[Byte], Int, Int]): Flow[ByteString, ByteString, NotUsed] =
yeah, I've changed, it in 9c85fc3 but there is an issue with binary compat. This part of code was copied from previous version of `lengthField` method which already been released. It is also in other methods in Framing (`delimiter`, `simpleFramingProtocol`). There are some options: or add overloadings or leave it as it is now.
WDYT @patriknw ?

2017-06-27 12:58 UTC, manonthegithub commented
There is binary compat issue when changing Int to Integer params. I can reset last two commits and leave it as it was or maybe it is better to add overloaded versions of this functions?

2017-06-27 14:59 UTC, johanandren commented
As the methods that are incompatible are not really usable as they are you can add the proposed filters to `project/MiMa.scala`

2017-06-27 16:07 UTC, manonthegithub commented
squashed, rebased and added Mima exclusions

2017-07-06 12:55 UTC, patriknw requested changes

2017-07-06 12:55 UTC, patriknw commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    maximumFrameLength: Integer,
this was a misunderstanding, those should still be `Int`, i.e. primitive `int` in java, the problem was only in `Function2[Array[Byte], Integer, Integer]`

remember to update MiMa also

2017-07-06 15:17 UTC, manonthegithub commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    maximumFrameLength: Integer,
sorry for that, I've corrected it

2017-07-07 11:48 UTC, patriknw approved these changes

2017-07-07 11:48 UTC, patriknw commented
thanks

2017-07-07 11:48 UTC, merged