Document ActorSystem termination
akka/akka pull request #22863
Opened 2017-05-07 03:10 UTC by richard-imaoka

Fixes #21840

Do these comments in the issue mean that 

- passing callbacks to `onComplete` or `onSuccess` of the `Future` from `whenTerminated` 

is preferred over 

- `registerOnTermination` ?

> I could have sworn `onTermination` was deprecated along with the `awaitTermination` methods.

> Yeah, was thinking my surprise about it not being deprecated out loud there. :)

2017-05-07 14:04 UTC, johanandren commented
I wanted to deprecate `registerOnTermination` while working on typed but I realised it was more work than worth it. 

In typed we will not have `registerOnTermination` though, so could be good to at least not push it as the choice.

I think the new `coordinated-shutdown` is a much better tool to gracefully shutdown things that should keep the actor system itself from terminating until done.

2017-05-07 16:37 UTC, richard-imaoka commented
Thanks, I wasn't aware of `coordinated-shutdown`. Let me look at it and update this PR accordingly, if needed.

2017-05-08 00:37 UTC, ktoso requested changes
Marking that needs changes; indeed we should explain coordinated shutdown more rather than those methods :)

2017-05-08 09:55 UTC, patriknw requested changes

2017-05-08 09:55 UTC, patriknw commented on akka-docs/rst/general/actor-systems.rst
> +You can call it multiple times to register multiple callbacks.
yes, this can be replaced by a mention and link to coordinated shutdown

2017-05-08 09:55 UTC, patriknw commented on akka-docs/rst/general/actor-systems.rst
> +callbacks with ``registerOnTermination`` are finished.
and then this last sentence can be removed

2017-05-08 09:55 UTC, patriknw commented on akka-actor/src/main/scala/akka/actor/ActorSystem.scala
> +   * Note that ActorSystem will not terminate until all the registered callbacks are finished.
this is still correct

2017-05-09 06:39 UTC, richard-imaoka commented on akka-docs/rst/general/actor-systems.rst
> +You can call it multiple times to register multiple callbacks.
sure, replaced in the new commit

2017-05-09 06:39 UTC, richard-imaoka commented on akka-docs/rst/general/actor-systems.rst
> +callbacks with ``registerOnTermination`` are finished.
removed in the new commit

2017-05-09 06:42 UTC, richard-imaoka commented
Replaced the mention to `registerOnTermination` with linkage to `CoordinatedShutdown`. As the existing `CoordinatedShutdown` section has decent explanation and sample code, I just added the hyperlink instead of rehearsing the same explanation.

2017-05-09 07:55 UTC, patriknw commented on akka-docs/rst/general/actor-systems.rst
> +look at ``CoordinatedShutdown`` [:ref:`Java <coordinated-shutdown-java>`, :ref:`Scala <routing-scala>`]
wrong ref for Scala

2017-05-09 10:17 UTC, richard-imaoka commented on akka-docs/rst/general/actor-systems.rst
> +look at ``CoordinatedShutdown`` [:ref:`Java <coordinated-shutdown-java>`, :ref:`Scala <routing-scala>`]
Sorry I was too stupid :| Fixed the ref and double-checked that both generated hyperlinks work as expected.

2017-05-09 12:40 UTC, patriknw approved these changes
LGTM

2017-05-09 12:40 UTC, merged