#22808 Move CoupledTerminationFlow to Flow.fromSinkAndSourceCoupled
akka/akka pull request #22876
Opened 2017-05-09 12:08 UTC by 2m

Fixes #22808

2017-05-09 12:39 UTC, patriknw approved these changes
LGTM

2017-05-10 02:52 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
> +  def fromSinkAndSourceCoupled[I, O](sink: Graph[SinkShape[I], _], source: Graph[SourceShape[O], _]): Flow[I, O, NotUsed] =
Great, really good to see these defined on Flow directly 👍  (good move)

2017-05-10 04:12 UTC, ktoso commented on akka-docs/rst/java/stream/stages-overview.rst
>  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
underscore should be aligned

2017-05-10 04:14 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
> +   * into the materialized value of the resulting [[Flow]].
Please add: 

```
The Sink and Source sides of a flow constructed like this are not "connected" in the sense that completion
of either side is independent. So if the Sink receives a completion signal, the Source side will remain unaware 
of that. If looking to "couple" the termination signals of the two sides use `fromSinkAndSourceCoupled` instead.
```

2017-05-10 04:14 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
> +   * will be sent to the Sink and the Flow's output will come from the Source.
please add the same doc note as I put below

2017-05-10 04:15 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
>     */
Please add this docs note here too https://github.com/akka/akka/pull/22876/files#r115651026

2017-05-10 04:15 UTC, ktoso requested changes
LGTM, after docs added and underlining fixed in stages-overview :)

2017-05-11 15:29 UTC, 2m commented
Added the missing scaladoc and fixed the formatting.

2017-05-11 15:30 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
> +   * of either side independent. So if the Sink receives a completion signal,
A bit weird sentence, maybe:

`The completion of the Sink and Source sides of a Flow constructed using this method are independent.`

2017-05-11 15:31 UTC, ktoso reviewed
Slight rewording please, LGTM then :)

2017-05-11 15:32 UTC, 2m commented on akka-stream/src/main/scala/akka/stream/javadsl/Flow.scala
> +   * of either side independent. So if the Sink receives a completion signal,
Yea. This sounds better. Thanks. I changed your original proposal since it had too much "quotes" around words. :)

2017-05-19 11:39 UTC, johanandren approved these changes
LGTM but waiting for a doc fix Konrad mentioned, right?

2017-05-19 13:02 UTC, 2m commented
Fix was already there. I have rebased and squashed.

2017-05-22 13:59 UTC, ktoso approved these changes
LGTM, thanks!

2017-05-22 14:00 UTC, ktoso commented
Thanks, great move :)

2017-05-22 14:00 UTC, merged