Converted reference docs to paradox
akka/akka pull request #22891
Opened 2017-05-10 11:12 UTC by raboof

Some known issues, but I think we can simply run the conversion again if
needed.

2017-05-10 11:48 UTC, patriknw commented
Shall we create a `akka-docs-new` branch instead, that we work on until it's ready to be be merged into master` Then we can place/replace things at the right place (`akka-docs`) immediately and we don't mess up git history by copying the sample code around.

2017-05-10 12:07 UTC, patriknw requested changes
Skimmed a small fraction of it and I think it's looking good, but as mentioned in other comment I think we should not copy sample code to avoid loosing git history. Would it even be worth doing a `git mv` of the old rst files to the new location before replacing the content?

2017-05-10 12:41 UTC, raboof commented
`git mv` for the example code seems like a good idea - and indeed then we need to use an `akka-docs-new` branch because that'd break the 'old' docs. Perhaps just merge https://github.com/pvlugter/akka/tree/wip/paradox into that, too?

Should we create issues to keep track of the various conversion TODO's?

2017-05-10 13:26 UTC, raboof commented
As discussed on slack: good idea, I'll create a new `wip-akka-docs-new` branch and properly `git mv` stuff in there

2017-05-10 14:45 UTC, raboof commented on akka-docs-new/src/main/paradox/additional/osgi.md
> +   Bundles should not export overlapping package spaces. It is not uncommon for legacy JVM frameworks to expect plugins
indeed odd, though renders fine

2017-05-10 15:03 UTC, raboof commented on akka-docs-new/src/main/paradox/common/circuitbreaker.md
> +*CircuitBreaker*
seems wrong, created #22897

2017-05-10 15:07 UTC, raboof commented on akka-docs-new/src/main/paradox/general/stream/stream-design.md
> +>
it seems this causes the bulleted list to be indented as well as bulleted. Not sure if that makes sense to me, but it's consistent between the RST and Paradox versions

2017-05-12 07:30 UTC, raboof commented
Work continues in `wip-akka-docs-new` instead

2017-05-12 07:30 UTC, closed without merging