Merge Akka Typed to master branch
akka/akka pull request #22999
Opened 2017-05-22 12:20 UTC by ktoso

2017-05-22 13:32 UTC, patriknw commented
test failure is unrelated to Akka Typed as far as I can see, created https://github.com/akka/akka/issues/23001

2017-05-22 13:32 UTC, patriknw commented
PLS BUILD

2017-05-22 13:32 UTC, ktoso commented
Was just looking at it, a bit weird - yes certainly unrelated

2017-05-22 13:40 UTC, patriknw requested changes

2017-05-22 13:40 UTC, patriknw commented on akka-docs/rst/java/index-actors.rst
> +Actors
nothing in `akka-docs/rst/` should be added

2017-05-22 13:40 UTC, patriknw commented on akka-docs/src/main/paradox/scala/typed.md
>  This module is currently marked as @ref:[may change](common/may-change.md) in the sense
there should be a java/typed.md also, I wrote that rst page and code examples (so it's only about converting it)

and it should be included in java/index-actors

2017-05-22 13:42 UTC, ktoso commented on akka-docs/rst/java/index-actors.rst
> +Actors
Whoops, merge mistake indeed - thanks!

2017-05-22 13:42 UTC, ktoso commented on akka-docs/src/main/paradox/scala/typed.md
>  This module is currently marked as @ref:[may change](common/may-change.md) in the sense
Ok cool, glad it already exists even :-)

2017-05-22 13:45 UTC, patriknw commented on project/MiMa.scala
> +        ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.remote.WireFormats#DeployDataOrBuilder.getScopeManifest")
not sure what happend here, perhaps not change anything in mima apart from the `watchWith` filter

2017-05-22 15:55 UTC, patriknw approved these changes
LGTM

2017-05-23 08:19 UTC, patriknw approved these changes
LGTM, the changes are in the expected files so I think it's good

2017-05-23 08:20 UTC, merged