[WORK IN PROGRESS] !typ #22970 Actor.restarter renamed to supervise
akka/akka pull request #23015
Opened 2017-05-23 12:32 UTC by ktoso

SOME TESTS ARE FAILING STILL - Will finish working on this after lunch.

Updated supervision API for Typed, with the following benefits:

- reads nicer: was `Actor.restarter[Something](...)` now is: `Actor.supervise(behavior).onFailure(howToDealWithIt)`

No default is picked, this has the benefit of:

- exposing people to the fact there's more to life than "restart"
  - esp interesting since now we can just use backoff supervision in those
- Java and Scala DSL look the same

2017-05-23 13:11 UTC, johanandren commented on akka-typed/project/build.properties
> +sbt.version=0.13.15
wut?!

2017-05-23 13:21 UTC, ktoso commented on akka-typed/project/build.properties
> +sbt.version=0.13.15
Oh, weird - will remove ofc.

2017-05-23 15:21 UTC, patriknw reviewed
I haven't looked at all details yet, but what I can see looks promising.

2017-05-23 19:44 UTC, ktoso commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +      val effectiveTag = if (tag == ClassTag(classOf[Nothing])) ClassTag(classOf[Throwable]) else tag
This is sneaky :-/
I'm open to any other ideas how to solve this. The problem is: sadly when someone would write `.onFailure(blabla)` (missing `[...]`), then Nothing would get inferred so we're attempting to match if a thing is Nothing, and not Throwable in the internals then.

I tried some type level hackery sadly that's not working : https://stackoverflow.com/questions/27912014/enforce-a-lower-bounds-that-excludes-a-super-type

2017-05-23 20:15 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +      val effectiveTag = if (tag == ClassTag(classOf[Nothing])) ClassTag(classOf[Throwable]) else tag
I think that is a good way. You should probably cache the ClassTag-Nothing

2017-05-23 20:15 UTC, ktoso commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +      val effectiveTag = if (tag == ClassTag(classOf[Nothing])) ClassTag(classOf[Throwable]) else tag
Cool, if we think that's fine then I'll just cache it and it'll work fine :)

2017-05-24 05:40 UTC, patriknw requested changes
looking great, one minor thing

also nice to see that we were able to change without touching the implementation, just as a confirmation that we did something right with the separation of api and impl

2017-05-24 05:40 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +      val effectiveTag = if (tag == NothingClassTag) ClassTag(classOf[Throwable]) else tag
`Throwable` tag should also be cached

2017-05-24 05:40 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/scaladsl/Actor.scala
> +   * val dbSpecificRestarts = supervise(dbConnector).onFailure[IndexOutOfBoundsException](SupervisorStrategy.resume) // handle all NonFatal exceptions
use `Actor.supervise` in examples

2017-05-24 06:32 UTC, johanandren approved these changes
LGTM

2017-05-24 06:32 UTC, johanandren commented on akka-typed/src/main/scala/akka/typed/javadsl/Actor.scala
> +  final class Supervise[T](wrapped: Behavior[T]) {
Make the constructor private/internal to give us some more bin comp freedom?

2017-05-24 06:33 UTC, johanandren commented
I think we should update that supervision blog article with a note about the renaming as well when this is released.

2017-05-24 07:21 UTC, patriknw commented
yes, I'll update the article and the example repo

2017-05-24 07:22 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/javadsl/Actor.scala
> +  final class Supervise[T](wrapped: Behavior[T]) {
+1 but it will not be visible from java

2017-05-24 07:23 UTC, patriknw commented on akka-typed/src/main/scala/akka/typed/javadsl/Actor.scala
> +  final class Supervise[T](wrapped: Behavior[T]) {
I mean, it will still show up as public from java (as usual)

2017-05-24 08:59 UTC, johanandren approved these changes
LGTM!

2017-05-24 09:00 UTC, patriknw approved these changes
LGTM

2017-05-24 09:14 UTC, patriknw commented
Refs #22970

2017-05-24 09:23 UTC, merged