=rem #23023 log reasons for disassociations with debug level
akka/akka pull request #23116
Opened 2017-06-07 11:56 UTC by jrudolph

I deprecated the old `disassociate` method for now but that might not be reasonable given that remoting classes are public API / SPI.

2017-06-07 12:47 UTC, patriknw requested changes
looking good

2017-06-07 12:47 UTC, patriknw commented on akka-remote/src/main/scala/akka/remote/transport/AkkaProtocolTransport.scala
> +            log.debug("Sending disassociate to {} because unexpected message was received during handshake {}", wrappedHandle, msg)
I think we should avoid full `toString` of messages, also on debug level, to not risk bad performance (or even OOME). Use the class name.

2017-06-07 12:47 UTC, patriknw commented on akka-remote/src/main/scala/akka/remote/transport/Transport.scala
> +  @deprecated
It's fine to deprecate it, but include version and comment as in other places

2017-06-14 09:35 UTC, jrudolph commented
Adressed review feedback.

2017-06-14 10:06 UTC, patriknw approved these changes
LGTM

2017-06-14 12:30 UTC, jrudolph commented
I added a mima filter. Notably, custom transport implementations compiled against old versions of akka-remote will fail to run with the new version. I don't think that's a likely scenario. Do we know about such a custom implementation for which that could be a problem?

2017-06-16 07:31 UTC, patriknw commented
custom transports are not encouraged, so I have no problem with breaking that :)

2017-06-16 07:43 UTC, patriknw approved these changes
LGTM, I'll backport

2017-06-16 07:43 UTC, merged