Merge scala/stream/stream-customize.md and java/stream/stream-customi…
akka/akka pull request #23181
Opened 2017-06-17 06:38 UTC by atiqsayyed

Identical contents in scala/stream/stream-customize.md and java/stream/stream-customize.md merged

2017-06-17 06:42 UTC, ktoso commented
OK TO TEST

2017-06-17 06:43 UTC, ktoso commented
Whoops, misclicked sorry :) Thanks a lot!

2017-06-19 09:36 UTC, raboof requested changes

2017-06-19 09:36 UTC, raboof commented on akka-docs/src/main/paradox/java/stream/stream-customize.md
> +../../scala/stream/stream-customize.md
Seems something went wrong here - the file was replaced by a file containing the contents "../../scala/stream/stream-customize.md", but it should have been replaced with a symlink. The difference is a bit hard to see in the github UI but should be clear when you build the docs locally. Could you make this a symlink?

2017-06-20 11:26 UTC, atiqsayyed commented
Sorry for the silly thing, updated the PR now :D

2017-06-20 11:32 UTC, raboof commented on akka-docs/src/main/paradox/scala/stream/stream-customize.md
> +stage has been completed. This can be done by overriding the `onUpstreamFinish` method in @scala[`InHandler`] @java[`AbstractInHandler`].
There's a spurious space here for the `scala` version

2017-06-20 15:50 UTC, raboof approved these changes

2017-06-20 15:51 UTC, merged

2017-06-20 15:51 UTC, raboof commented
Thanks!