added complex frame size support in framing #22129 (backport)
akka/akka pull request #23211
Opened 2017-06-21 14:25 UTC by patriknw

(cherry picked from commit b936ac641c9aaa993d054d414eca010cbef1f11f)

Refs #22129

2017-06-26 15:34 UTC, ktoso approved these changes
LGTM

2017-06-26 15:57 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    computeFrameSize:   akka.japi.function.Function2[Array[Byte], Int, Int]): Flow[ByteString, ByteString, NotUsed] =
Whoop! Warning, should this not be Integers instead?

2017-06-26 15:59 UTC, ktoso requested changes
Whoop, signature in java method is bad here. This becomes `Function2<byte[], Object, Object>` in java (see comment in line)

2017-06-27 07:04 UTC, patriknw commented on akka-stream/src/main/scala/akka/stream/javadsl/Framing.scala
> +    computeFrameSize:   akka.japi.function.Function2[Array[Byte], Int, Int]): Flow[ByteString, ByteString, NotUsed] =
great catch

2017-07-06 12:56 UTC, patriknw commented
this still needs another round of backporting when the original PR has been updated

2017-07-07 12:02 UTC, patriknw commented
I have updated this with the latest from the other PR, so can be merged when validated.

2017-07-07 12:03 UTC, patriknw commented
And for the record, this is perhaps not the kind of feature we would normally backport but it was a customer request.

2017-07-07 14:28 UTC, merged