Move name parameter to 2nd pos. in typed system factories
akka/akka pull request #23244
Opened 2017-06-28 08:52 UTC by hseeberger

See #23241.

2017-06-28 10:39 UTC, patriknw approved these changes
LGTM, thanks

2017-06-28 11:04 UTC, ktoso requested changes
One more API which needs change. LGTM otherwise

2017-06-28 11:04 UTC, ktoso commented on akka-typed/src/main/scala/akka/typed/ActorSystem.scala
>    def create[T](name: String, guardianBehavior: Behavior[T]): ActorSystem[T] =
Please change the order in the create method too

2017-06-28 11:28 UTC, hseeberger commented on akka-typed/src/main/scala/akka/typed/ActorSystem.scala
>    def create[T](name: String, guardianBehavior: Behavior[T]): ActorSystem[T] =
Thanks for noticing. Fixed.

2017-07-02 23:56 UTC, ktoso approved these changes
Looks good now, thanks!

2017-07-04 07:13 UTC, merged