Merge paradox/scala/remoting-artery.md and java/remoting-artery.md
akka/akka pull request #23258
Opened 2017-06-29 17:09 UTC by richard-imaoka

Refs #23052

## Rendered HTML:

- https://richard-akka-doc.firebaseapp.com/scala/remoting-artery.html
- https://richard-akka-doc.firebaseapp.com/java/remoting-artery.html

## I split this in two commits:

- **1st commit:** Identical contents in scala/remoting-artery.md and java/remoting-artery.md -> **this is to take the diff both in scala/remoting-artery.md and java/remoting-artery.md**

  - [scala/remoting-artery.md  (prev) vs. scala/remoting-artery.md (after)](https://github.com/richard-imaoka/akka/commit/de2953dc0d2a7a260c940d6e0733c72f593d4614#diff-6b5751e179e615bfced810beb83e3a83)
  - [java/remoting-artery.md (prev) vs. java/remoting-artery.md (after)](https://github.com/richard-imaoka/akka/commit/de2953dc0d2a7a260c940d6e0733c72f593d4614#diff-ea0d7e75a212482d96bea4003425ad3d)

- **2nd commit:** Replace java/remoting-artery.md with a symlink to scala/remoting-artery.md

2017-06-29 21:28 UTC, raboof requested changes
Thanks for another nice merge! Some nitpicks here and there

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +backwards compatible with the old implementation and it is a drop-in replacement in many cases. Main features
Hmm 'source compatible' might be slightly more accurate here?

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +    @@@
The Scala and Java snippet bodies are switched here

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +:   @@@vars
Do we need `@@@vars` here?

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +It is also security best practice to @ref:[disable the Java serializer](#disabling-the-java-serializer) because of
I think we prefer `@ref` without `:`

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +it should be complemented with @ref[disabled Java serializer](#disabling-the-java-serializer)
:+1:

2017-06-29 21:28 UTC, raboof commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +    akka.remote.artery..trusted-selection-paths = ["/user/receptionist", "/user/namingService"]
A `.` too many here it seems

2017-07-01 22:40 UTC, richard-imaoka commented on akka-docs/src/main/paradox/java/remoting-artery.md
> +:   @@@vars
Is it not only for this place but generally for in-line code snippets **_not_** using `${property}` values? 

If we should remove unnecessary `@@@vars`  from in-line snippets, I can create a separate PR updating **_other_** .md files. (Of course I can fix remoting-artery.md in this PR)

2017-07-01 22:41 UTC, richard-imaoka commented
Sorry it seems like I left many of small issues to be fixed. I reflected your review comments - let me know if it looks better now.

2017-07-03 15:22 UTC, raboof requested changes
Almost there 2 small tweaks needed!

2017-07-03 15:22 UTC, raboof commented on akka-docs/src/main/paradox/scala/remoting-artery.md
> +    ```
Scala/java snippets seem to be reversed here

2017-07-03 15:22 UTC, raboof commented on akka-docs/src/main/paradox/scala/remoting-artery.md
> +    @@@
and here too

2017-07-03 15:22 UTC, raboof commented on akka-docs/src/main/paradox/scala/remoting-artery.md
> +    @@@
Looks like this is the same for Java and Scala - perhaps make it just a normal snippet without tabs?

2017-07-04 12:47 UTC, raboof approved these changes

2017-07-04 12:47 UTC, raboof commented
Thanks, looks good!

2017-07-04 12:47 UTC, merged