add log messages for buffer fill percent #25253
akka/akka pull request #23254
Opened 2017-06-28 19:26 UTC by abesanderson

Log fill percent on SourceQueue buffer every 10% at info, after 50% at warning.

2017-06-29 06:50 UTC, ktoso commented
Refs #23253

2017-06-29 06:54 UTC, ktoso requested changes
I'm not convienced this is a clean way to add logging. This way we'd end up having tens of methods with a boolean for logging... Rather perhaps we could introduce an Attribute called debug logging that could be specifically enabled on sections of a stream (which is better than a global debug flag for those) - though I guess the logging would have to be `val shouldLog = globalDebugEnabled || logDebugAttributePresent`

2017-06-29 06:54 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/scaladsl/Source.scala
> +  def queue[T](bufferSize: Int, overflowStrategy: OverflowStrategy, logBufferFill: Boolean = false): Source[T, SourceQueueWithComplete[T]] =
this is breaking API and can not be done in such form.

2017-06-29 06:54 UTC, ktoso commented
OK TO TEST

2017-06-29 15:11 UTC, patriknw commented
I agree that we must have a better solution. If it's plain debug logging I think it can just be added without any flags, but then there are categories like "verbose debug logging" and warnings. Attributes could be a nice way for streams.

2017-06-29 22:18 UTC, abesanderson commented
Adding into attributes for a per-stage flag seems pretty straightforward, not quite sure where to add things for a global debug.  There is a global setting in the materializer, but I don't see any examples where those materializer settings are put into the stage logic.  Maybe a setting for `akka.stream.debug-logging`, though again, I don't really see other examples in the code of passing typesafe config to a stage.  For this case, I think it falls under the category of warnings...just something to give a bit of preliminary idea if buffers are filling.

2017-07-07 04:24 UTC, ktoso commented
> . Maybe a setting for akka.stream.debug-logging, though again, I don't really see other examples in the code of passing typesafe config to a stage.

Any stage can get that via: ``

However what we should to is go via attributes I believe, so a stage would get those via `attributes.get[ActorAttributes.VerboseLogging /*thats the new thing to introduce*/]`

2017-07-10 15:50 UTC, ktoso reviewed
Looks pretty good now, just needs docs on the object/method and another eye to look at it :)

2017-07-10 15:50 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/impl/QueueSource.scala
> +    val verboseLogging = inheritedAttributes.contains(VerboseLogging)
exactly 👍

2017-07-10 15:50 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/Attributes.scala
> +  val verboseLogging: Attributes = Attributes(VerboseLogging)
good, needs some docs on the method as well as on the object.
Docs could be something like "enables verbose logging in stages that chose to support it. Such logging can be useful when debugging unexpected behaviour in element passing, however should not be used in day-to-day use as it likely will result in too vast amounts of logs" or something like that?

2017-07-10 15:50 UTC, ktoso commented on akka-stream/src/main/scala/akka/stream/Attributes.scala
> +  val verboseLogging: Attributes = Attributes(VerboseLogging)
I think it's fine to put on Attributes btw; Initially was thinking about ActorAttributes but here is fine 👍

2017-07-10 17:46 UTC, lightbend-cla-validator commented
Hi @xdev-developer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2017-07-10 17:47 UTC, abesanderson commented
>< Royally hosed up rebasing to the master.

2017-07-10 18:10 UTC, abesanderson commented on akka-stream/src/main/scala/akka/stream/Attributes.scala
> +  val verboseLogging: Attributes = Attributes(VerboseLogging)
Think this description should work....part of what I was adding for was getting buffer information, so wanted to include that note as well.

2017-09-12 12:36 UTC, patriknw approved these changes
LGTM, please rebase

2017-09-25 14:13 UTC, jrudolph reviewed
I can see why this would be useful, however, I have two concerns here:

 * It seems ad-hoc to add this kind of logging to a single stage
 * This change currently proposes to log the fill level at INFO level in 10% increments and to escalate to WARNING at 50% full. These numbers seem arbitrary and should be configurable.

Looking at the bigger picture, we should provide ways to observe these kinds of internal state (e.g. as metrics). The actual threshold and triggers for logging (or responding in other ways) should not have to be built into the stages themselves.

Currently lacking a general interface to provide metrics / state information to the use, I wonder if we could provide these values for the queue stage in another way? For the queue, adding API could be quite simple as we already have an external interface that would allow querying the state.

2017-09-26 14:44 UTC, abesanderson commented
@jrudolph That's fair enough.  Those cutoffs simply mimicked what was logged on the cluster sharding(another area where a buffer is used instead of backpressure).  To explain where I was coming from: QueueSource seems one of the few recourses when backpressuring is not available, but there is no way(that I'm aware of) to get any sort of health state of the queue.  In the case that manual intervention has to be taken, I didn't have any alerting or notification I was getting into a bad state.  I can easily configure my queue size, which gave me more of a window of time to correct, but no way to see the problem was occurring until it was already too late and dropping messages.  I think the need I saw could be eliminated as well if more of the metrics of stream rates, buffer fill, etc, were available to users.  I do have access to the commercial tools, which provides metrics on actors, but nothing(yet) for streams.

2017-09-26 14:56 UTC, patriknw commented
I think @jrudolph has a very valid point. As we discussed lately we should probably try to find more holistic solution to all such metrics, diagnostics, health, ...
That is not something we can request in this PR and will involve considerable work by the core team. Shall we include the logging from this PR in the meantime? Wdyt @jrudolph ?

2019-03-28 17:46 UTC, abesanderson commented
It's been quite some time since I started this one, but I believe it may largely be unnecessary with some of the features added since this was created.  If I recall, the situation I was trying to stop was triggered because I had a stream that was feeding into PersistentActor and the cluster sharding was getting slammed with a flood of messages that recovery couldn't keep up with.  The addition of #22638(limit number of concurrent recoveries) helped to mitigate the original issue a lot.  There still may be a need to grab stats from within the QueueSource, but I think that ultimately, it is better solved by backpressuring from the downstream consumers.

2019-03-28 17:46 UTC, closed without merging