Introduce missing team role if necessary (#23243)
akka/akka pull request #23252
Opened 2017-06-28 16:33 UTC by raboof

When receiving gossip from a node that did not contain any team
information (such as gossip from a node running a previous version of
Akka), add the default team role during deserialization.

2017-06-30 02:42 UTC, ktoso commented
Refs #23243

2017-06-30 08:54 UTC, patriknw requested changes
good solution, but perhaps perf could be improved

2017-06-30 08:54 UTC, patriknw commented on akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
> +    }
looks somewhat expensive. Not sure what collection type the `getRolesIndexesList.asScala` is. Perhaps we could iterate the raw java List and build the `Set` in a more efficient way than `++`?

2017-06-30 15:38 UTC, Hawstein commented on akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
> +      case Seq(head, tail @ _*) ⇒
Why not here just use:

```
  case Nil => blabla
  case head :: tail => blabla
```

2017-07-01 05:13 UTC, Hawstein commented on akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
> +      case Seq(head, tail @ _*) ⇒
Oh, i know. Because at the call site, this method is given a `mutable.Buffer[Integer]`.

2017-07-01 05:15 UTC, Hawstein commented on akka-cluster/src/main/scala/akka/cluster/protobuf/ClusterMessageSerializer.scala
> +    }
Indeed. `getRolesIndexesList.asScala` is a `JListWrapper` which extends `mutable.Buffer`. `tail` costs `O(n)` instead of `O(1)`

2017-07-03 13:54 UTC, raboof commented
Superseded by #23276

2017-07-03 13:54 UTC, closed without merging