Fix link the actor lifecycle
akka/akka pull request #23300
Opened 2017-07-06 00:36 UTC by vitornp

2017-07-06 08:33 UTC, raboof requested changes
Thanks for noticing and taking the time to propose this improvement! I think we can do even better, could you consider using `@ref` here?

2017-07-06 08:33 UTC, raboof commented on akka-docs/src/main/paradox/scala/guide/tutorial_1.md
> +The family of these lifecycle hooks is rich, and we recommend reading [the actor lifecycle](http://doc.akka.io/docs/akka/current/scala/actors.html#actor-lifecycle) section of the reference for all de
Hmm, I guess we should really make this a `@ref[]` link so in the future [paradox can check it](https://github.com/lightbend/paradox/issues/120), could you make that change?

2017-07-07 10:59 UTC, vitornp commented
@raboof Change for `@ref`

2017-07-07 14:03 UTC, raboof requested changes

2017-07-07 14:03 UTC, raboof commented on akka-docs/src/main/paradox/scala/guide/tutorial_1.md
> +The family of these lifecycle hooks is rich, and we recommend reading @ref:[the actor lifecycle](actors.html#actor-lifecycle) section of the reference for all details.
I'm afraid the syntax is `@ref[the actor lifecycle](../actors.md#actor-lifecycle)` - you can run 'sbt paradox' to test but I appreciate that's not so easy from the GitHub UI :)

2017-07-10 15:17 UTC, raboof commented
PLS BUILD

2017-07-10 16:28 UTC, vitornp commented
PLS BUILD

2017-07-10 16:30 UTC, raboof approved these changes
Thanks, LGTM when Jenkins agrees :)

2017-07-10 19:19 UTC, vitornp commented
@raboof Jenkins automatic start?

2017-07-10 21:34 UTC, raboof commented
Hmm, it should but apparently didn't

2017-07-10 21:34 UTC, raboof commented
PLS BUILD

2017-07-11 07:10 UTC, johanandren approved these changes

2017-07-11 07:11 UTC, merged