Merge content of stream graphs.md
akka/akka pull request #23455
Opened 2017-07-29 14:50 UTC by naferx

Ref #23052

2017-07-29 14:51 UTC, naferx commented
@raboof  This PR is ready for review

2017-07-31 12:01 UTC, raboof requested changes
Looks pretty good, I noticed a couple of 'empty' `@java[ ]` directives, these can be removed entirely. Almost ready to go!

2017-07-31 12:01 UTC, raboof commented on akka-docs/src/main/paradox/scala/stream/stream-graphs.md
> +or ending a `Flow`. @scala[Junctions must always be created with defined type parameters, as otherwise the `Nothing` type
Perhaps remove the `@java[ ]` and move the `.` inside the `@scala[...]`?

2017-07-31 18:15 UTC, naferx commented on akka-docs/src/main/paradox/scala/stream/stream-graphs.md
> +or ending a `Flow`. @scala[Junctions must always be created with defined type parameters, as otherwise the `Nothing` type
Done

2017-07-31 18:37 UTC, raboof approved these changes
Looks good thanks!

2017-07-31 18:38 UTC, merged