Make sending messages to dead letters by DistributedPubSubMediator configurable. #23462
akka/akka pull request #23615
Opened 2017-09-10 17:51 UTC by RafalSumislawski

I've implemented a configuration property for disabling sending messages to dead letters by DistributedPubSubMediator as proposed in #23462.

Adding a field to DistributedPubSubSettings results in binary compatibility issue reported by MiMa.
```
[info] akka-cluster-tools: found 1 potential binary incompatibilities while checking against com.typesafe.akka:akka-cluster-tools_2.11:2.4.9  (filtered 5)
[error]  * method this(scala.Option,akka.routing.RoutingLogic,scala.concurrent.duration.FiniteDuration,scala.concurrent.duration.FiniteDuration,Int)Unit in class akka.cluster.pubsub.DistributedPubSubSettings does not have a correspondent in current version
```
I'm not sure how it should be handled. Adding a second constructor without that parameter is an option. Is that what I should do?

2017-09-10 17:51 UTC, lightbend-cla-validator commented
Hi @RafalSumislawski,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2017-09-10 17:53 UTC, ktoso commented
OK TO TEST

2017-09-12 12:16 UTC, patriknw requested changes
looking good, one small change

2017-09-12 12:16 UTC, patriknw commented on akka-cluster-tools/src/main/scala/akka/cluster/pubsub/DistributedPubSubMediator.scala
> +  val sendToDeadLettersWhenNoSubscribers: Boolean) extends NoSerializationVerificationNeeded {
The new parameter must be added in a binary backwards compatible way, i.e. add another (deprecated) constructor corresponding to the old constructor

2017-09-13 20:30 UTC, RafalSumislawski commented
I've added a constructor corresponding to the old one. Now `mimaReportBinaryIssues` passes. The CI build failed on some tests, which are unrelated to my changes (and did pass locally).

2017-09-25 07:32 UTC, johanandren commented
PLS BUILD

2017-09-25 09:12 UTC, patriknw approved these changes
LGTM

2017-09-25 09:14 UTC, raboof approved these changes
Nice feature and well-tested PR!

2017-09-25 09:15 UTC, merged