Drops `Source.combine` instance method (#22452)
akka/akka pull request #23641
Opened 2017-09-14 21:41 UTC by nadavwr

It was most likely put there by pasting accident—no equivalents exist on `Sink` or in `javadsl`, and the implementation is identical to the `combine` method on the companion object—which means it discards the source being operated on.

2017-09-14 21:42 UTC, nadavwr commented
This resolves the bugfixing aspect of #22452

2017-09-15 07:58 UTC, johanandren requested changes
We cannot drop that even if it had weird semantics because of our binary compatibility guarantees. Instead mark it with deprecated so that we can remove it in the next major Akka version.

2017-09-15 07:59 UTC, ktoso commented
Yup, as @johanandren said

2017-09-16 21:43 UTC, nadavwr commented
Continuing [here](https://github.com/akka/akka/pull/23645)

2017-09-16 21:43 UTC, closed without merging