Introduce 'PersistentActorContext' and ctx.persist()
akka/akka pull request #23680
Opened 2017-09-21 09:55 UTC by raboof

I'm not sure yet whether I like it: while it does get rid of the
extra generic parameters when using `andThen`, it is kind of confusing
to expose both `Persist()` and `ctx.persist()`, and I'm not a big fan of
the latter because it looks so much like a side-effect even though it isn't.

I wonder if modeling the `andThen` as an `Effect` and having a function to
concatenate effects would turn out nicer.

2017-09-21 10:13 UTC, patriknw commented
I like the idea of having `andThen` as an `Effect`, a `SideEffect`.
The chaining can be `andThen`.
```
Persist(evt).andThen(SideEffect(state => ctx.sender() ! state)).andThen(Stop())
```

2017-09-21 11:28 UTC, ktoso commented
Did not review the entire thing, but `ctx.persist` is very misleading, esp for people migrating or having mixed codebases etc. The `andThen(SideEffect` looks very lovely though, and very explicit :)

2017-09-21 11:28 UTC, ktoso requested changes
Not a fan of `ctx.persist()`, we should try other approaches

2017-09-22 08:58 UTC, raboof commented
Agreed the chained effects turned out nicer

2017-09-22 08:58 UTC, closed without merging