Remove redundant Futures tests (#24095)
akka/akka pull request #24130
Opened 2017-12-09 15:54 UTC by catalin-ursachi

Fixes #24095.

I've removed every test that was obviously irrelevant to Akka. The remaining ones look like they're covered by the tests in `AskSpec`, though; should I just delete FutureSpec altogether?

2017-12-09 15:56 UTC, ktoso commented
OK TO TEST

2017-12-09 16:09 UTC, catalin-ursachi commented
The error looks spurious & unrelated to the changes, as far as I can tell?

2017-12-11 10:17 UTC, johanandren requested changes

2017-12-11 10:17 UTC, johanandren commented on akka-actor-tests/src/test/scala/akka/pattern/AskSpec.scala
> +        case v                               ⇒ fail(v + " was not Failure(AskTimeoutException)")
Good

2017-12-11 10:17 UTC, johanandren commented on akka-actor-tests/src/test/scala/akka/dispatch/FutureSpec.scala
> +object FutureSpec {
I think you can remove the entire test file as ask has tests in `AskSpec`

2017-12-11 15:14 UTC, johanandren approved these changes
LGTM

2018-01-16 07:05 UTC, patriknw commented
OK TO TEST

2018-01-16 07:06 UTC, patriknw commented
PLS BUILD

2018-01-16 07:06 UTC, patriknw approved these changes
LGTM

2018-01-16 07:45 UTC, merged