Allow tagging in persistence typed (#23817)
akka/akka pull request #24217
Opened 2017-12-30 11:24 UTC by richardimaoka

To illustrate the behavior, I have a code snippet in [gist](https://gist.github.com/richardimaoka/d5183d783cdf04ff97e1e9f5f570d369), and tested it using cassandra persistence plugin. 

By supplying a tagging function as follows:

```scala
taggingFunction = _ => Seq("mytag1", "mytag2")
```
I got event rows with tags correctly:

![2017-12-30_20h14_23](https://user-images.githubusercontent.com/7414320/34453731-ad445b60-ed9e-11e7-8612-2acae99a87d8.png)

Without a tagging function,

```scala
//taggingFunction = _ => Seq("mytag1", "mytag2")
```

no tags are added as expected.

![2017-12-30_20h15_16](https://user-images.githubusercontent.com/7414320/34453732-ad6ea4f6-ed9e-11e7-85db-9a46ed968a5d.png)

2018-01-01 11:02 UTC, chbatey requested changes
Thanks @richardimaoka

Would you mind adding documentation for this? It'll be in akka-docs/src/main/paradox/persistence-typed.md you can add an example to the akka/akka-persistence-typed/src/test/scala/akka/persistence/typed/scaladsl/PersistentActorCompileOnlyTest.scala as the inmem journal doesn't support tagging.

Also should we not make the function Event => Set[String] ? Makes no sense to allow the same tag twice.

Also what do we want to call the parameter? taggingFunction seems odd to me as it is obviously a function from the type signature. Other things are called handlers but you don't really "handle" tags, you create them. Maybe just tagger?

2018-01-02 16:57 UTC, patriknw requested changes

2018-01-02 16:57 UTC, patriknw commented on akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentActorImpl.scala
> +      val eventToPersist = if (tags.size > 0) Tagged(event, tags.toSet) else event
`tags.nonEmpty` instead of `tags.size > 0`

2018-01-02 16:57 UTC, patriknw commented on akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentActorImpl.scala
> +      val eventToPersist = if (tags.size > 0) Tagged(event, tags.toSet) else event
or perhaps reverse the condition, `tags.isEmpty`

2018-01-02 16:57 UTC, patriknw commented on akka-persistence-typed/src/main/scala/akka/persistence/typed/internal/PersistentActorImpl.scala
> +          if (tags.size > 0) Tagged(event, tags.toSet) else event
^

2018-01-02 16:57 UTC, patriknw commented on akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentActor.scala
> +    taggingFunction:            Event ⇒ Seq[String]                   = (_: Event) ⇒ Seq.empty): PersistentBehavior[Command, Event, State] =
An alternative is to add it to `PersistentBehavior`, similar to `onRecoveryCompleted`. That might make more sense since it's an optional feature.

2018-01-02 16:57 UTC, patriknw commented on akka-persistence-typed/src/main/scala/akka/persistence/typed/scaladsl/PersistentActor.scala
> +    taggingFunction:            Event ⇒ Seq[String]                   = (_: Event) ⇒ Seq.empty): PersistentBehavior[Command, Event, State] =
use `Set` instead of `Seq`

2018-01-03 05:42 UTC, richardimaoka commented
Thanks for the feedback! Let me reflect the review comments in a few days.

2018-01-13 20:48 UTC, richardimaoka commented
Reflected review comments but [failing in Jenkins](https://jenkins.akka.io:8498/job/pr-validator-per-commit-jenkins/11254/console)

What is this error?

```
[error] sbtwhitesource.WhiteSourceException: Error communicating with service: Bad Gateway
[error] 	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:382)
[error] 	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:364)
[error] 	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:68)
```

2018-01-16 09:47 UTC, chbatey commented
PLS BUILD

2018-01-17 13:20 UTC, patriknw approved these changes
LGTM

2018-01-17 13:20 UTC, merged