fail fast if Typed Cluster.sharding.spawn is called several times wit…
akka/akka pull request #24555
Opened 2018-02-15 10:21 UTC by shkoder

ref #23708

 * maintain a map in ClusterShardingImpl to track type names and class names
 * fix a bug in ClusterShardingImpl.spawnWithMessageExtractor - actually use allocationStrategy param
 * remove unused calls/imports in untyped ClusterSharding

2018-02-15 15:13 UTC, johanandren commented
OK TO TEST

2018-02-19 10:09 UTC, patriknw requested changes
suggestion for better check in case of concurrent access

2018-02-19 10:09 UTC, patriknw commented on akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
> +    }
I think this is too early, see below

2018-02-19 10:09 UTC, patriknw commented on akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
>          untypedSharding.internalStart(
this will happily return the previous ref for the "typeKey.name" if it was already registered

2018-02-19 10:09 UTC, patriknw commented on akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
> +    typeNames.put(typeKey.name, typeKey.asInstanceOf[EntityTypeKeyImpl[A]].messageClassName)
I think it's here we can do the check with `typeNames.putIfAbsent`

2018-02-19 14:30 UTC, patriknw approved these changes
LGTM

2018-02-19 14:30 UTC, patriknw commented on akka-cluster-sharding-typed/src/main/scala/akka/cluster/sharding/typed/internal/ClusterShardingImpl.scala
> +        throw new IllegalArgumentException(s"${typeKey.name} already spawned for $spawnedMessageClassName")
even though not consistent everywhere we try to use brackets around such fields in exception and log messages:

```
s"[${typeKey.name}] already spawned for [$spawnedMessageClassName]"
```

2018-02-20 13:54 UTC, johanandren approved these changes
LGTM, thanks!

2018-02-20 13:55 UTC, merged