= util add Throwables helper to help fatal checking of Throwable for …
akka/akka pull request #24661
Opened 2018-03-05 19:55 UTC by hepin1989

…Java,alias with Scala's Nonfatal pattern matching.

2018-03-06 01:06 UTC, ktoso commented on akka-actor/src/main/scala/akka/util/Throwables.scala
> +object Throwables {
needs docs why this exists and what the intended use case is -- to allow catching only non fatal ones in supervision on routing in akka http I suppose

2018-03-06 01:07 UTC, ktoso approved these changes
I can see this adding value to our Java DSL offering... perhaps it should be in a javadsl package though, or `akka.japi`

2018-03-06 02:07 UTC, hepin1989 commented
Yes，I extracted it from our inner project, it's really needed when we want to achieve the same sematic as it is in Scala.

`japi` is a good fit place too.

2018-03-06 04:07 UTC, hepin1989 commented
@ktoso Ping

2018-03-06 04:08 UTC, ktoso commented
No need to ping, already got 2 emails before you pinged. Things will be reviewed in their time.

2018-03-06 04:14 UTC, hepin1989 commented
Haha, Sorry for the bother:)

2018-03-06 08:22 UTC, johanandren commented
I can see how it is useful, but does it really belong in Akka?

2018-03-06 08:42 UTC, hepin1989 commented
And then use it as 
![image](https://user-images.githubusercontent.com/501740/37022260-5f4a2654-215d-11e8-9dd5-80fa295b42d6.png)

We don't need this in Scala:)

2018-03-06 09:10 UTC, johanandren commented
That does not change my assessment, I see that it is useful, but is it really something a toolkit for concurrency and distributed systems should provide, as I see it it is filling out a void in the standard library rather (and we can't provide fillers for all those gaps in the scope of Akka)

2018-03-06 14:28 UTC, patriknw commented
What about using `scala.util.control.NonFatal` instead? The only difference is the naming:

```java
import scala.util.control.NonFatal;

   try {
     // dangerous stuff
   } catch(Throwable e) {
     if (NonFatal.apply(e)){
       log.error(e, "Something not that bad.");
     } else {
       throw e;
     }
```

2018-03-07 04:19 UTC, ktoso commented
The NonFatal PR (this one) I can see being valuable, since Java people tend to panic once they have to touch a scala class. The other PR I think was going too far, but this I'd be ok with. Esp if wanting to implement same semantics things in Java, for Alpakka or Akka HTTP, this method would help.

Unless someone feels strongly against it

2018-03-07 10:35 UTC, patriknw commented
I'm ok with adding it. Will comment on the implementation, though.

2018-03-07 10:37 UTC, patriknw requested changes

2018-03-07 10:37 UTC, patriknw commented on akka-actor/src/main/scala/akka/japi/Throwables.scala
> +  def isNonFatal(throwable: Throwable): Boolean = throwable match {
can be:
```
def isNonFatal(throwable: Throwable): Boolean = NonFatal(throwable)
```

2018-03-07 10:38 UTC, ktoso commented on akka-actor/src/main/scala/akka/japi/Throwables.scala
> +  def isNonFatal(throwable: Throwable): Boolean = throwable match {
Good one!

2018-03-09 08:13 UTC, ktoso approved these changes
Was amended, LGTM

2018-03-09 08:14 UTC, merged