DSL ActorContext extends typed ActorContext #24823
akka/akka pull request #24829
Opened 2018-04-01 14:42 UTC by rkuhn

2018-04-01 14:43 UTC, rkuhn commented
fixes #24823

2018-04-02 07:30 UTC, chbatey approved these changes
LGTM, i don't see a downside to this unless we want to make interpretMessage internal

2018-04-03 18:23 UTC, patriknw requested changes
I think this is a good change.

This will expose `asJava` in javadsl and `asScala` scaladsl, but that's not too bad.

A few internal casts can now be removed, search for "asInstanceOf.*ActorContext" in akka-actor-typed

2018-04-07 08:11 UTC, ktoso commented on akka-actor-typed/src/main/scala/akka/actor/typed/internal/BehaviorImpl.scala
> +          val b = Behavior.validateAsInitial(Behavior.start(d, ctx.as[t]))
How could I have missed that we have such `as[]`, was missing it a few times

2018-04-11 09:28 UTC, patriknw approved these changes
LGTM, thanks

2018-04-11 09:28 UTC, merged