Documentation of wrapping PersistentBehavior in typed actor persistence #24679
akka/akka pull request #24942
Opened 2018-04-21 18:55 UTC by rasouli

addressing issue #24679 on documentation of wrapping PersistentBehavior inside other Behavior construct.

* Removed "Current Limitations" section
* Added description on wrapping PersistentBehavior
* Added Scala and Java example for the pattern

2018-04-23 05:50 UTC, chbatey commented
OK TO TEST

2018-04-23 05:54 UTC, chbatey requested changes
Thanks, couple of nits

2018-04-23 05:54 UTC, chbatey commented on akka-docs/src/main/paradox/typed/persistence.md
> +When creating/setting up `PersistentBehavior`, it is possible to wrap `PersistentBehaviors` in
I think just "creating a" reads better

2018-04-23 05:54 UTC, chbatey commented on akka-docs/src/main/paradox/typed/persistence.md
> +When creating/setting up `PersistentBehavior`, it is possible to wrap `PersistentBehaviors` in
wrap a `PersistentBehavior` rather than PersistentBehaviors as it is just the factory.

2018-04-23 05:54 UTC, chbatey commented on akka-docs/src/main/paradox/typed/persistence.md
> +other behaviors such as `Behaviors.setup` in order to access `ActorContext` object. For instance
access the `ActorContext` object

2018-04-30 16:50 UTC, rasouli commented
@chbatey  please review.

2018-05-01 06:30 UTC, chbatey approved these changes
LGTM

2018-05-01 06:30 UTC, chbatey commented
Thanks @rasouli

2018-05-02 15:05 UTC, rasouli commented
@ktoso please review.

2018-05-03 08:20 UTC, patriknw approved these changes
LGTM

2018-05-03 08:20 UTC, merged