Clarify mailbox configuration entry location
akka/akka pull request #25071
Opened 2018-05-08 21:14 UTC by jchapuis

It is not clear that mailbox configuration entry when used independently of a dispatcher needs to be located at the top level of the configuration, and not nested inside of the `akka` block

2018-05-08 21:14 UTC, lightbend-cla-validator commented
Hi @jchapuis,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2018-05-09 07:02 UTC, johanandren requested changes

2018-05-09 07:02 UTC, johanandren commented on akka-docs/src/main/paradox/mailboxes.md
> +mailbox type to be used (note that this needs to be a top-level section).
I think "an absolute config path" would be more clear, it does not need to be a top level section AFAIR

2018-05-14 16:26 UTC, lightbend-cla-validator commented
Hi @jchapuis,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2018-05-14 16:30 UTC, johanandren commented
I updated it to a wording I find more correct, but even with such a small change I think we would need the CLA ok from you @jchapuis

2018-05-17 06:15 UTC, jchapuis commented
LGTM, thanks @johanandren !

2018-05-17 07:31 UTC, johanandren commented
Thanks! I'll try to figure out why the cla-validator is still whining.

2018-05-17 07:51 UTC, raboof reviewed
:+1: noticed a tiny thing

2018-05-17 07:51 UTC, raboof commented on akka-docs/src/main/paradox/mailboxes.md
> +mailbox type to be used (note that this needs to be a an absolute config path,
'a an'

2018-05-17 09:22 UTC, raboof approved these changes

2018-05-21 14:06 UTC, johanandren approved these changes

2018-05-21 14:06 UTC, merged