Add deprecation documentation to bin-compat docs
akka/akka pull request #25400
Opened 2018-07-28 04:34 UTC by JustinPihony

Closes #25399

2018-07-29 07:01 UTC, ktoso commented on akka-docs/src/main/paradox/common/binary-compatibility-rules.md
> +Once a method has been deprecated then it will be kept, at minimum, for one **full** major version release. For example, if it is deprecated in version 2.5.2 then it will remain through the rest of 2
This is somewhat misleading still. Since those are minor versions, akka since 2.4 uses major.minor.patch after all.

2018-07-29 07:11 UTC, ktoso commented
I think we’ll need to think pretty intensely about the wording here. Because previously the wording that “remains in for a full major release cycle” was a nice mnemonic but not sure what we’ll do now hmm

2018-07-29 18:11 UTC, patriknw reviewed
Although this has been the rule of thumb there has been exceptions where a mistake or plain rename has been removed earlier. Especially in Akka HTTP. Keeping the deprecation long enough but not longer has been used as argument. E.g. 6 months should be long enough. While I have been promoting this rule of ”a full minor cycle” I can understand the arguments of making it possible to remove earlier sometimes.

2018-07-29 22:41 UTC, JustinPihony commented
Thanks. I actually had always thought 2nd digit was major since that is where binary compatibility and other things are locked in. I can easily change major to minor, however Patrik's comment makes me rethink that. How about something like this (we can clean it up if you like the sentiment):

> Once a method has been deprecated then the guideline* is that it will be kept, at minimum, for one **full** minor version release. For example, if it is deprecated in version 2.5.2 then it will remain through the rest of 2.5, as well as the entirety of 2.6. 
>
> *This is a guideline because in **rare** instances, after careful consideration, an exception may be made and the method removed earlier.

2018-08-08 06:38 UTC, raboof commented
OK TO TEST

2018-08-08 09:50 UTC, ktoso requested changes
Marking that this needs more discussion

2018-08-24 07:50 UTC, patriknw commented
I think the [latest suggestion](
https://github.com/akka/akka/pull/25400#issuecomment-408711286) is good.

Perhaps we can clarify the exception case further by adding something like:

In those cases the deprecated API will not be removed earlier than 6 months from when the deprecation was introduced.

2018-09-05 10:34 UTC, patriknw commented
@JustinPihony Can you update the PR with the latest suggestion. I think that is a good clarification, but still leaves some room for exceptions. Perhaps skip the 6 months part that I added because if there is a good reason we might want it to be even shorter. One example is the security vulnerability of the RNGs, that we deprecated and want to remove in ~ 2 months.

2018-09-06 00:18 UTC, JustinPihony commented
Updated - I opted to enter it as I noted in comments because a true footnote would be too far removed from the section imho. But if you want I can make it a true footnote for the extra note.

2018-09-06 07:37 UTC, patriknw approved these changes
LGTM, thanks @JustinPihony

2018-09-19 07:11 UTC, ktoso approved these changes
Wording is good now, thanks a lot @JustinPihony !

2018-09-19 07:11 UTC, ktoso commented
The failure was the $code$ issue we fixed last night. Merging this

2018-09-19 07:12 UTC, merged