Adds Flow.asFlowWithContext
akka/akka pull request #26372
Opened 2019-02-13 12:49 UTC by skyluc

Adds `Flow.asFlowWithContext()` function.
It allows to have symmetry with the existing `FlowWithContext.asFlow()`, `Source.asSourceWithContext()` and `SourceWithContext.asSource` functions (being renamed in #26353).

The main purpose of this function is to reduce the boilerplate code needed to integrate with a flow which is using some context information, but which is not using `FlowWithContext`.

2019-02-15 07:45 UTC, patriknw commented
OK TO TEST

2019-02-15 07:49 UTC, patriknw approved these changes
LGTM

2019-02-15 07:49 UTC, patriknw commented on akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
> +Turns a Folw into a FlowWithContext which can propagate a context per element along a stream.
typo Folw

2019-02-21 14:34 UTC, hseeberger requested changes
Nice feature! I have two comments hopefully improving the wording of the docs.

2019-02-21 14:34 UTC, hseeberger commented on akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
> +The first function passed into asFlowWithContext must turn incoming elements and contexts into elements of the flow, for every incoming elements.
Maybe rephrase "must turn each incoming pair of element and context value into an element of this Flow"

2019-02-21 14:34 UTC, hseeberger commented on akka-docs/src/main/paradox/stream/operators/Flow/asFlowWithContext.md
> +The second function passed into asFlowWithContext must turn elements into contexts, one context for every element.
Maybe rephrase as "must turn each outgoing element of this Flow into an outgoing context value"

2019-02-21 17:54 UTC, skyluc commented
Updated for #26419

Thanks @hseeberger for the comments.

2019-03-04 15:32 UTC, johanandren approved these changes
LGTM, I must have missed reviewing this before somehow, sorry!

2019-03-04 15:32 UTC, merged