Small tweaks to all command aliases
akka/akka pull request #26403
Opened 2019-02-18 11:58 UTC by chbatey

* Adds other cluster all commands
* Makes allCluster do all cluster modules

My normally terrible intuition thinks `allCuster` should do all cluster related thing which is something I often want to do when working on core cluster as I don't find out I've broken something in a cluster module until PR validation..

WDYT @helena ?

2019-02-18 13:22 UTC, patriknw approved these changes
LGTM

2019-02-18 13:22 UTC, patriknw commented on build.sbt
> +  commandValue(clusterTools)).mkString)
👍

2019-02-19 18:27 UTC, helena commented on CONTRIBUTING.md
> +If you dont want to run all tests and just want to check that everything is formatted/mima passes there
```suggestion
If you have already run all tests and now just need to check that everything is formatted and or mima passes there
```

2019-02-19 18:29 UTC, helena requested changes
Great addition! I'd make that one change clearer somehow, that the expectation is you've run tests. These tasks shouldn't slow anyone down, hence running 'test' is not included.

2019-02-21 14:12 UTC, merged