Adds to and toMap to SourceWithContext
akka/akka pull request #26412
Opened 2019-02-19 09:56 UTC by skyluc

Updated tests to use the new functions.

2019-02-21 10:17 UTC, johanandren requested changes
Looks good but missing the corresponding signatures in `akka.stream.javadsl.SourceWithContext`

2019-02-22 13:27 UTC, johanandren approved these changes
LGTM

2019-03-04 14:41 UTC, patriknw commented on akka-stream-tests/src/test/scala/akka/stream/scaladsl/SourceWithContextSpec.scala
> +        .run
shouldn't `SourceWithContext` also have `runWith` for consistency with ordinary `Source`, making this typical case more convenient

2019-03-05 08:20 UTC, patriknw commented
Cont in https://github.com/akka/akka/pull/26464

2019-03-05 08:20 UTC, closed without merging