add eager completion option for zipLatest
akka/akka pull request #29054
Opened 2020-05-10 08:42 UTC by contrun

Reference: https://github.com/akka/akka/issues/25839

2020-07-07 13:23 UTC, ennru approved these changes
Sorry for not getting to this earlier.
LGTM.

2020-07-07 13:24 UTC, ennru commented
But Mima is not that happy about the new parameter: https://travis-ci.org/github/akka/akka/jobs/685257534#L308

2020-07-07 16:29 UTC, contrun commented
@ennru Yeah. I saw the problem, but I didn't come up with a solution yet. I don't know how to circumvent it.

2020-07-08 06:58 UTC, ennru requested changes
Mima complains for good reasons. I added the old constructor in the generator pattern.
Avoid default values to parameters in APIs that intend to stay backwards compatible.
To make this work, you'll need a new method name in `FlowOps` to disambiguate the methods.

This PR lacks a Java DSL counterpart.

2022-04-27 05:12 UTC, hepin1989 commented
@raboof @johanandren hi team, @contrun have updated this PR, any inputs?

2022-04-29 08:37 UTC, ennru commented on akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
> +   *   '''Completes when''' any upstream completes if `eagerComplete` is enabled or wait for all upstreams to complete
This method signature doesn't have the `eagerComplete` parameter.
```suggestion
   *   '''Completes when''' any of the upstreams completes
```

2022-04-29 08:37 UTC, ennru commented on akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
> +   *   '''Completes when''' any of the upstreams completes
```suggestion
   *   '''Completes when''' any upstream completes if `eagerComplete` is enabled or wait for all upstreams to complete
```

2022-04-29 08:37 UTC, ennru commented on akka-stream/src/main/scala/akka/stream/scaladsl/Flow.scala
> +  //TODO exclude this in mima ,this method is not used.
```suggestion
```

2022-04-29 08:37 UTC, ennru commented on akka-stream-tests/src/test/scala/akka/stream/scaladsl/GraphZipLatestWithSpec.scala
> +    setup(p1, p2, eagerComplete = false)
Eager completion should stay to be the default, correct?

2022-04-29 08:37 UTC, ennru commented on akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
> +  def apply[A, B](): ZipLatest[A, B] = new ZipLatest()
Doc comment missing.

2022-04-29 08:37 UTC, ennru commented on akka-stream/src/main/scala/akka/stream/scaladsl/Graph.scala
> + * '''Completes when''' any upstream completes if `eagerComplete` is enabled or wait for all upstreams to complete
Unzip doesn't change.

2022-04-29 10:04 UTC, ennru approved these changes
LGTM.

2022-05-04 12:35 UTC, johanandren approved these changes
LGTM, thanks!

2022-05-04 12:36 UTC, merged