Document reference.conf appending on gradle+kotlin
akka/akka pull request #29274
Opened 2020-06-18 19:42 UTC by raboof

2020-06-19 13:39 UTC, ldeluigi commented
Good for me.

2020-06-19 13:41 UTC, ldeluigi requested changes
Maybe it could be less verbose with the two tabs (Groovy/Kotlin) that show the different styles.

2020-06-23 06:12 UTC, johanandren approved these changes

2020-06-25 07:33 UTC, ennru approved these changes
LGTM.

2020-06-25 08:11 UTC, merged