Fix supervision sample project link
akka/akka pull request #30006
Opened 2021-02-05 21:43 UTC by grimlor

Per [this linked conversation thread](https://typesafe.slack.com/archives/C1ETEPM36/p1612549367066100), this addresses a broken link to the Supervision sample project in the Supervision and Monitoring page of the Akka docs by hard-linking it specifically for the 2.5 docs. 

It would be beneficial to include a similar link in the 2.6 documentation for Classic Actors Supervision since it's still applicable, I believe.

2021-02-05 21:43 UTC, lightbend-cla-validator commented
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

2021-02-08 09:28 UTC, johanandren approved these changes

2021-02-08 09:42 UTC, johanandren requested changes
Actually, we removed that sample because it was not correct, so better to drop the link completely instead. https://github.com/akka/akka-samples/issues/131

2021-03-15 16:38 UTC, closed without merging

2021-03-15 16:39 UTC, johanandren commented
Thanks for the PR highlighting that the link was broken, I created a new PR removing the link completely instead so closing this.